import type { HintLanguage } from "@/lib/i18n";

export type AstroCopy = readonly [string, string, string, string, string];
export const astroText = (language: HintLanguage, copy: AstroCopy) =>
  copy[({ en: 0, zh: 1, es: 2, ja: 3, ko: 4 } as const)[language]];
const copy = {
  room: [
    "THE CELESTIAL ATELIER",
    "月光星象室",
    "EL ATELIER CELESTE",
    "月光のアトリエ",
    "달빛 아틀리에",
  ],
  title: [
    "A sky of your own",
    "属于你的天空",
    "Un cielo propio",
    "あなただけの空",
    "나만의 하늘",
  ],
  intro: [
    "Discover the signs. Find yourself in the details.",
    "认识星座，在细节里探索自己。",
    "Descubre los signos. Explórate en los detalles.",
    "星座を知り、その奥にある自分を探す。",
    "별자리를 알아보고, 그 안에서 나를 발견해요.",
  ],
  explore: [
    "Explore signs",
    "探索星座",
    "Explorar signos",
    "星座を知る",
    "별자리 탐색",
  ],
  chart: ["My chart", "我的星盘", "Mi carta", "私のチャート", "나의 차트"],
  now: [
    "Transits now",
    "此刻行运",
    "Tránsitos",
    "今のトランジット",
    "현재 트랜짓",
  ],
  sections: [
    "Astrology sections",
    "占星分区",
    "Secciones de astrología",
    "占星術のセクション",
    "점성술 메뉴",
  ],
  building: [
    "A language, layer by layer",
    "一层一层，读懂星象",
    "Un lenguaje por capas",
    "ひとつずつ、星の言葉を",
    "한 겹씩 알아가는 별의 언어",
  ],
  difference: [
    "Your sign is a beginning. Your chart is the whole conversation.",
    "星座是起点，星盘让不同配置展开对话。",
    "Tu signo es el inicio. Tu carta reúne toda la conversación.",
    "星座は入り口。チャートは、配置どうしの対話です。",
    "별자리는 시작이에요. 차트는 여러 배치가 나누는 대화예요.",
  ],
  planets: ["Planets", "行星", "Planetas", "天体", "천체"],
  signs: ["Signs", "星座", "Signos", "星座", "별자리"],
  houses: ["Houses", "宫位", "Casas", "ハウス", "하우스"],
  what: ["The theme", "什么主题", "El tema", "テーマ", "주제"],
  how: ["The expression", "如何表达", "La expresión", "表し方", "표현 방식"],
  where: ["The life area", "生活领域", "El ámbito", "生活の領域", "삶의 영역"],
  library: [
    "Twelve ways of being",
    "十二种表达方式",
    "Doce formas de ser",
    "12の表現のかたち",
    "열두 가지 표현 방식",
  ],
  learning: [
    "Zodiac guide · general learning",
    "星座指南 · 一般知识",
    "Guía zodiacal · aprendizaje general",
    "星座ガイド・一般的な知識",
    "별자리 가이드 · 일반 지식",
  ],
  signNote: [
    "These are tropical zodiac signs, not astronomical constellations or personality diagnoses.",
    "这里介绍回归黄道星座，并非天文学星座区域或性格诊断。",
    "Son signos del zodiaco tropical, no constelaciones astronómicas ni diagnósticos de personalidad.",
    "ここではトロピカル方式の星座を扱います。天文学の星座領域や性格診断とは異なります。",
    "열대황도 별자리를 다뤄요. 천문학의 별자리 구역이나 성격 진단은 아니에요.",
  ],
  backSigns: [
    "All twelve signs",
    "返回十二星座",
    "Los doce signos",
    "12星座に戻る",
    "열두 별자리로",
  ],
  everyday: [
    "In everyday life",
    "生活中的样子",
    "En la vida cotidiana",
    "日常では",
    "일상에서",
  ],
  reflection: [
    "A question to sit with",
    "留给自己的问题",
    "Una pregunta para ti",
    "自分に問いかける",
    "나에게 건네는 질문",
  ],
  yourPlacements: [
    "This sign in your chart",
    "你星盘中的这个星座",
    "Este signo en tu carta",
    "あなたのチャートでは",
    "내 차트 속 이 별자리",
  ],
  noneInSign: [
    "No returned placements are in this sign.",
    "已返回的配置中，没有行星落在这个星座。",
    "Ninguna posición recibida está en este signo.",
    "取得した配置に、この星座の天体はありません。",
    "반환된 배치 중 이 별자리에 위치한 천체가 없어요.",
  ],
  create: [
    "Create my birth chart",
    "建立我的星盘",
    "Crear mi carta natal",
    "出生図を作る",
    "출생 차트 만들기",
  ],
  setupTitle: [
    "The moment you arrived",
    "你来到世界的那一刻",
    "El momento en que llegaste",
    "あなたが生まれた瞬間",
    "세상에 도착한 순간",
  ],
  setupCopy: [
    "Your date, time and place of birth bring your chart into focus. Start here, on this device — no email needed.",
    "出生日期、时间和地点，让星盘有据可依。直接在此设备建立，不需要先填写邮箱。",
    "La fecha, hora y lugar de nacimiento dan forma a tu carta. Empieza en este dispositivo, sin correo electrónico.",
    "生年月日・時刻・場所から出生図を作ります。この端末ですぐ始められ、メールは不要です。",
    "생년월일, 시간, 장소로 차트를 만들어요. 이메일 없이 이 기기에서 시작할 수 있어요.",
  ],
  unknownTime: [
    "Time unknown? Save what you know. We won’t invent a Moon, Ascendant or houses.",
    "时间未知？先保存已知资料。我们不会猜测月亮、上升或宫位。",
    "¿No sabes la hora? Guarda lo que sabes. No inventaremos la Luna, el Ascendente ni las casas.",
    "時刻が不明でも保存できます。月・アセンダント・ハウスを推測で補いません。",
    "시간을 모르나요? 아는 정보만 저장해요. 달, 상승점, 하우스를 임의로 채우지 않아요.",
  ],
  birth: [
    "Birth details",
    "出生资料",
    "Datos de nacimiento",
    "出生データ",
    "출생 정보",
  ],
  review: [
    "Review birth details",
    "确认出生资料",
    "Revisar datos",
    "出生データを確認",
    "출생 정보 확인",
  ],
  reviewNote: [
    "Check the date, time and selected place before saving. Chart positions depend on these details.",
    "保存前请检查日期、时间和已选择的地点，星盘位置取决于这些资料。",
    "Revisa la fecha, hora y lugar antes de guardar. Las posiciones dependen de estos datos.",
    "保存前に日付・時刻・場所をご確認ください。配置はこの情報に基づきます。",
    "저장 전에 날짜, 시간, 장소를 확인해요. 이 정보가 차트의 기준이에요.",
  ],
  save: [
    "Save on this device",
    "保存到此设备",
    "Guardar en este dispositivo",
    "この端末に保存",
    "이 기기에 저장",
  ],
  edit: [
    "Edit birth details",
    "编辑出生资料",
    "Editar datos",
    "出生データを編集",
    "출생 정보 수정",
  ],
  back: ["Back", "返回", "Volver", "戻る", "뒤로"],
  local: [
    "Saved on this device",
    "已存此设备",
    "Guardado en este dispositivo",
    "この端末に保存済み",
    "이 기기에 저장됨",
  ],
  notStored: [
    "Chart available in this session. It could not be saved on this device.",
    "星盘在本次使用中可读，但尚未成功保存到此设备。",
    "La carta está disponible en esta sesión, pero no se pudo guardar en el dispositivo.",
    "今回のセッションでは読めますが、端末への保存に失敗しました。",
    "현재 세션에서 볼 수 있지만 기기에 저장하지 못했어요.",
  ],
  retrySave: [
    "Retry saving chart",
    "重试保存星盘",
    "Reintentar guardar",
    "保存を再試行",
    "차트 저장 재시도",
  ],
  saveError: [
    "Birth details could not be saved. Your entries are still here; please retry.",
    "出生资料保存失败，填写内容仍在，请重试。",
    "No se pudieron guardar los datos. Siguen aquí; inténtalo de nuevo.",
    "出生データを保存できませんでした。入力内容は残っています。再試行してください。",
    "출생 정보를 저장하지 못했어요. 입력 내용은 남아 있으니 다시 시도해요.",
  ],
  calculate: [
    "Calculate birth chart",
    "计算出生星盘",
    "Calcular carta natal",
    "出生図を計算",
    "출생 차트 계산",
  ],
  calculating: [
    "Calculating your chart…",
    "正在计算星盘…",
    "Calculando tu carta…",
    "チャートを計算中…",
    "차트 계산 중…",
  ],
  chartError: [
    "A calculated chart is unavailable right now. Your birth details are saved; you can retry.",
    "暂时无法取得计算星盘。出生资料已保存，可以重试。",
    "La carta calculada no está disponible ahora. Tus datos están guardados; puedes reintentar.",
    "計算結果を取得できませんでした。出生データは保存済みです。再試行できます。",
    "계산된 차트를 가져오지 못했어요. 출생 정보는 저장되어 있으며 재시도할 수 있어요.",
  ],
  incomplete: [
    "Save an accurate birth time and a place with verified coordinates and time zone to calculate personal placements.",
    "请补齐准确出生时间，以及已确认坐标和时区的地点，再计算个人配置。",
    "Añade la hora exacta y un lugar con coordenadas y zona horaria verificadas para calcular posiciones personales.",
    "個人の配置を計算するには、正確な時刻と座標・タイムゾーンが確認された出生地が必要です。",
    "개인 배치를 계산하려면 정확한 출생 시간과 좌표·시간대가 확인된 장소가 필요해요.",
  ],
  birthSky: [
    "Your sky at birth",
    "出生时的天空",
    "Tu cielo al nacer",
    "生まれたときの空",
    "태어났을 때의 하늘",
  ],
  chartIntro: [
    "One moment. Many ways to be you. Begin with your three personal anchors, then explore the connections.",
    "同一个瞬间，映出多面的你。从三大配置开始，再探索它们之间的联系。",
    "Un momento, muchas formas de ser tú. Empieza por tus tres puntos personales y explora sus conexiones.",
    "ひとつの瞬間に、いくつものあなた。まず3つの配置から、つながりを探りましょう。",
    "한순간에 담긴 여러 모습의 나. 세 가지 주요 배치부터 연결을 살펴봐요.",
  ],
  wheel: [
    "Your celestial signature",
    "你的星象印记",
    "Tu firma celeste",
    "あなたの星のしるし",
    "나의 천체 서명",
  ],
  wheelHelp: [
    "Select a point or use the list below. The positions are calculated; the reflections are an educational guide.",
    "点选星点或使用下方列表。位置来自计算，反思文字是知识解读。",
    "Selecciona un punto o usa la lista. Las posiciones están calculadas; las reflexiones son una guía educativa.",
    "点を選ぶか、下のリストをご利用ください。配置は計算値、解説は学習のためのガイドです。",
    "점을 선택하거나 아래 목록을 이용해요. 위치는 계산값이며 해석은 학습용 안내예요.",
  ],
  zoom: [
    "Enlarge chart",
    "放大星盘",
    "Ampliar carta",
    "チャートを拡大",
    "차트 확대",
  ],
  placements: [
    "Planet placements",
    "行星配置",
    "Posiciones planetarias",
    "天体の配置",
    "천체 배치",
  ],
  aspects: ["Aspects", "相位", "Aspectos", "アスペクト", "각"],
  unavailable: [
    "Not supplied",
    "未提供",
    "No disponible",
    "未提供",
    "제공되지 않음",
  ],
  evidence: [
    "Based on this calculated placement",
    "依据此项实际配置",
    "Basado en esta posición calculada",
    "この計算済み配置に基づく解説",
    "이 계산된 배치를 바탕으로",
  ],
  house: ["House", "宫位", "Casa", "ハウス", "하우스"],
  retrograde: ["Retrograde", "逆行", "Retrógrado", "逆行", "역행"],
  retroNote: [
    "Retrograde describes apparent backward motion as seen from Earth. It is not a prediction of failure.",
    "逆行指从地球观察到的视运动方向，不是失败的预言。",
    "Retrógrado describe el movimiento aparente hacia atrás visto desde la Tierra. No predice un fracaso.",
    "逆行は地球から見た見かけの後退です。失敗を予言するものではありません。",
    "역행은 지구에서 볼 때 거꾸로 움직이는 듯한 현상이에요. 실패의 예언이 아니에요.",
  ],
  calculated: ["Calculated", "计算时间", "Calculado", "計算日時", "계산 시각"],
  system: [
    "Tropical zodiac · house system",
    "回归黄道 · 宫位系统",
    "Zodiaco tropical · sistema de casas",
    "トロピカル方式・ハウス方式",
    "열대황도 · 하우스 체계",
  ],
  returnedOnly: [
    "Only returned points are shown. Missing houses or aspects are not filled in.",
    "仅显示实际返回的点位，缺少的宫位或相位不会补造。",
    "Solo se muestran los datos recibidos. No se rellenan casas ni aspectos ausentes.",
    "取得した配置のみ表示します。不明なハウスやアスペクトは補いません。",
    "반환된 위치만 표시해요. 누락된 하우스나 각은 임의로 채우지 않아요.",
  ],
  refresh: ["Recalculate", "重新计算", "Recalcular", "再計算", "다시 계산"],
  transitTitle: [
    "The sky, in conversation",
    "此刻天空，与出生星盘对话",
    "El cielo en conversación",
    "今の空との対話",
    "현재 하늘과의 대화",
  ],
  transitIntro: [
    "Transits connect the moving sky to your fixed natal placements. This is different from a general Sun-sign horoscope.",
    "行运将当下天空与固定的出生配置相连，与一般太阳星座运势不同。",
    "Los tránsitos conectan el cielo actual con tus posiciones natales fijas. Difieren de un horóscopo general por signo solar.",
    "トランジットは今の天体と出生時の配置を結びます。太陽星座だけの運勢とは異なります。",
    "트랜짓은 현재 하늘과 고정된 출생 배치를 연결해요. 일반적인 태양 별자리 운세와 달라요.",
  ],
  today: ["Today", "今日", "Hoy", "今日", "오늘"],
  week: ["This week", "本周", "Esta semana", "今週", "이번 주"],
  transitError: [
    "Personal transits are unavailable. Your birth chart remains available. Please retry.",
    "暂时无法取得个人行运，出生星盘仍可查看，请重试。",
    "Los tránsitos no están disponibles. Tu carta natal sigue disponible. Reintenta.",
    "トランジットを取得できませんでした。出生図は引き続き閲覧できます。再試行してください。",
    "개인 트랜짓을 가져오지 못했어요. 출생 차트는 계속 볼 수 있어요. 다시 시도해요.",
  ],
  loading: ["Loading…", "读取中…", "Cargando…", "読み込み中…", "불러오는 중…"],
  moving: [
    "Moving planet",
    "当下行星",
    "Planeta en tránsito",
    "今の天体",
    "현재 천체",
  ],
  natal: [
    "Natal placement",
    "出生配置",
    "Posición natal",
    "出生時の配置",
    "출생 배치",
  ],
  noTransits: [
    "No transits were returned for this calculation. This does not predict an easy or difficult day.",
    "此次计算未返回行运，并不代表今天一定顺利或困难。",
    "El cálculo no devolvió tránsitos. Esto no predice un día fácil o difícil.",
    "この計算ではトランジットが返されませんでした。一日の良し悪しを示すものではありません。",
    "이번 계산에서 트랜짓이 반환되지 않았어요. 하루의 좋고 나쁨을 예측하는 뜻은 아니에요.",
  ],
  timing: [
    "Timing and context",
    "时间与依据",
    "Tiempo y contexto",
    "時期と背景",
    "시기와 맥락",
  ],
  starts: ["Starts", "开始", "Inicio", "開始", "시작"],
  exact: [
    "Exact aspect",
    "精确相位",
    "Aspecto exacto",
    "正確なアスペクト",
    "정확한 각",
  ],
  ends: ["Ends", "结束", "Fin", "終了", "종료"],
  orb: ["Orb", "容许度", "Orbe", "オーブ", "오브"],
  missingSelection: [
    "This selection was not returned in your current chart.",
    "当前星盘未返回所选配置。",
    "Esta selección no se recibió en tu carta actual.",
    "この配置は現在のチャートに含まれていません。",
    "현재 차트에서 이 배치가 반환되지 않았어요.",
  ],
  noTiming: [
    "Exact timing was not supplied.",
    "未提供精确时间。",
    "No se proporcionó la hora exacta.",
    "正確な時刻は提供されていません。",
    "정확한 시각은 제공되지 않았어요.",
  ],
  together: [
    "The space between you",
    "你们之间的星空",
    "El espacio entre ustedes",
    "ふたりの間にある空",
    "우리 사이의 하늘",
  ],
  togetherIntro: [
    "Two charts, real connections. Explore relationship themes without a compatibility score.",
    "两张星盘，真实配置联系。探索关系主题，不以分数定义关系。",
    "Dos cartas, conexiones reales. Explora temas de relación sin una puntuación de compatibilidad.",
    "ふたつのチャートのつながりを、相性スコアではなく関係のテーマとして読みます。",
    "두 차트의 실제 연결을 살펴봐요. 관계를 점수로 정의하지 않아요.",
  ],
  preview: [
    "Deeper reports · in preview",
    "深入报告 · 预览",
    "Informes ampliados · vista previa",
    "詳細レポート・プレビュー",
    "심층 보고서 · 미리보기",
  ],
  previewNote: [
    "Full personal reports are not available yet. Your calculated placements and learning library are available now.",
    "完整个人报告尚未提供。已计算配置和知识库现在即可探索。",
    "Los informes personales completos aún no están disponibles. Ya puedes explorar tus posiciones y la biblioteca.",
    "詳細な個人レポートは準備中です。計算済み配置と学習ガイドは利用できます。",
    "전체 개인 보고서는 준비 중이에요. 계산된 배치와 학습 가이드는 이용할 수 있어요.",
  ],
  footer: [
    "A space for reflection, not a fixed prediction. Birth details stay with your local device profile; no cross-device account sync.",
    "用于自我反思，不是确定预测。出生资料属于此设备的本机档案，不提供跨设备账号同步。",
    "Un espacio para reflexionar, no una predicción fija. Los datos pertenecen al perfil local, sin sincronización de cuentas entre dispositivos.",
    "確定した予言ではなく、振り返りのための場所です。出生データはこの端末のプロフィールに属し、端末間のアカウント同期はありません。",
    "확정된 예언이 아닌 성찰의 공간이에요. 출생 정보는 이 기기의 프로필에 속하며 기기 간 계정 동기화는 없어요.",
  ],
} satisfies Record<string, AstroCopy>;
export type AstroCopyKey = keyof typeof copy;
export const at = (language: HintLanguage, key: AstroCopyKey) =>
  astroText(language, copy[key]);
export const ASTRO_COPY = copy;
