import type { HintLanguage } from "../../lib/i18n";
import type { PlanetBody, ZodiacSign } from "../../types/astrology";
import { astroText, type AstroCopy } from "./astrologyCopy";

export const SIGN_ORDER: ZodiacSign[] = ["aries", "taurus", "gemini", "cancer", "leo", "virgo", "libra", "scorpio", "sagittarius", "capricorn", "aquarius", "pisces"];
export const SIGN_SYMBOLS = ["♈", "♉", "♊", "♋", "♌", "♍", "♎", "♏", "♐", "♑", "♒", "♓"];
const names: Record<ZodiacSign, AstroCopy> = {
  aries: ["Aries", "白羊座", "Aries", "牡羊座", "양자리"], taurus: ["Taurus", "金牛座", "Tauro", "牡牛座", "황소자리"],
  gemini: ["Gemini", "双子座", "Géminis", "双子座", "쌍둥이자리"], cancer: ["Cancer", "巨蟹座", "Cáncer", "蟹座", "게자리"],
  leo: ["Leo", "狮子座", "Leo", "獅子座", "사자자리"], virgo: ["Virgo", "处女座", "Virgo", "乙女座", "처녀자리"],
  libra: ["Libra", "天秤座", "Libra", "天秤座", "천칭자리"], scorpio: ["Scorpio", "天蝎座", "Escorpio", "蠍座", "전갈자리"],
  sagittarius: ["Sagittarius", "射手座", "Sagitario", "射手座", "사수자리"], capricorn: ["Capricorn", "摩羯座", "Capricornio", "山羊座", "염소자리"],
  aquarius: ["Aquarius", "水瓶座", "Acuario", "水瓶座", "물병자리"], pisces: ["Pisces", "双鱼座", "Piscis", "魚座", "물고기자리"],
};
export function signName(sign: ZodiacSign, language: HintLanguage): string { return astroText(language, names[sign]); }

const elements: AstroCopy[] = [["Fire", "火象", "Fuego", "火", "불"], ["Earth", "土象", "Tierra", "地", "흙"], ["Air", "风象", "Aire", "風", "공기"], ["Water", "水象", "Agua", "水", "물"]];
const modalities: AstroCopy[] = [["Cardinal", "基本模式", "Cardinal", "活動宮", "활동궁"], ["Fixed", "固定模式", "Fijo", "不動宮", "고정궁"], ["Mutable", "变动模式", "Mutable", "柔軟宮", "변동궁"]];
type ArticleCopy = { theme: AstroCopy; description: AstroCopy; example: AstroCopy; question: AstroCopy; sun: AstroCopy; moon: AstroCopy; rising: AstroCopy };
export type SignArticle = Record<keyof ArticleCopy | "element" | "modality", string>;

const articles: Record<ZodiacSign, ArticleCopy> = {
  aries: {
    theme: ["Begin with courage", "带着勇气开始", "Empezar con valor", "勇気をもって始める", "용기 있게 시작하기"],
    description: ["Aries symbolizes the spark that starts something. Its directness becomes more useful when initiative leaves room for other people's pace.", "白羊座象征迈出第一步的火花。主动与直接，也可以为别人的节奏留出空间。", "Aries simboliza la chispa que inicia algo. Su franqueza resulta más útil cuando deja espacio al ritmo de los demás.", "牡羊座は、物事を始める火花の象徴です。率直な行動に、相手のペースを待つ余白を加えてみましょう。", "양자리는 무언가를 시작하는 불꽃을 상징해요. 솔직한 추진력에 다른 사람의 속도를 존중할 여유를 더해 보세요."],
    example: ["You volunteer to start a shared project, then ask everyone how they want to contribute.", "在合作项目里先提出一个起点，再询问大家想如何参与。", "Te ofreces para iniciar un proyecto y preguntas cómo quiere contribuir cada persona.", "共同の企画で最初の一歩を提案し、みんなの関わり方も聞いてみる。", "공동 프로젝트의 첫걸음을 제안한 뒤, 각자 어떻게 참여하고 싶은지 물어봐요."],
    question: ["Where would one small, brave beginning help more than another round of preparation?", "在哪里，一个勇敢的小开始比继续准备更有帮助？", "¿Dónde ayudaría más un pequeño comienzo valiente que seguir preparándote?", "準備を重ねるより、小さく勇気を出して始めたいことは？", "계속 준비하기보다 작고 용감한 시작이 필요한 곳은 어디인가요?"],
    sun: ["Sun in Aries explores identity through initiative: choosing an action without needing to win every exchange.", "太阳白羊以主动行动探索自我，不必把每次交流都变成输赢。", "El Sol en Aries explora la identidad tomando iniciativa, sin convertir cada intercambio en una competición.", "太陽が牡羊座なら、主体的に動くことが自己表現のテーマ。毎回勝つ必要はありません。", "양자리 태양은 주도적인 행동으로 자신을 표현하는 주제예요. 모든 대화에서 이길 필요는 없어요."],
    moon: ["Moon in Aries links emotional expression with immediacy. Movement and a pause can both make room for a feeling.", "月亮白羊象征直接的情绪表达。行动与暂停，都可以给感受一点空间。", "La Luna en Aries vincula la emoción con lo inmediato. Moverte y hacer una pausa pueden dar espacio a lo que sientes.", "牡羊座の月は、その場の感情を率直に表す象徴。動くことも、一息つくことも助けになります。", "양자리 달은 감정을 즉각 표현하는 상징이에요. 몸을 움직이거나 잠시 멈추는 것 모두 감정을 위한 여유가 될 수 있어요."],
    rising: ["Aries rising describes a direct approach to unfamiliar situations, not a requirement to be fearless.", "白羊上升描述面对新情境时直接的方式，并不要求你无所畏惧。", "El ascendente Aries describe una entrada directa en lo desconocido, no la obligación de no sentir miedo.", "牡羊座のアセンダントは、新しい場へ率直に入る姿勢。怖さを感じてはいけない、という意味ではありません。", "양자리 상승점은 낯선 상황에 곧바로 다가가는 방식을 말해요. 두려움이 없어야 한다는 뜻은 아니에요."],
  },
  taurus: {
    theme: ["Make room for steadiness", "给稳定留一点空间", "Dar espacio a la constancia", "落ち着きを育てる", "꾸준함을 위한 자리"],
    description: ["Taurus symbolizes sustaining what matters through patience and tangible care. Steadiness can support change as well as protect familiar comforts.", "金牛座象征用耐心与实际照顾，维持重要的事物。稳定不只保护熟悉的舒适，也能支持改变。", "Tauro simboliza cuidar lo importante con paciencia y gestos concretos. La estabilidad también puede sostener el cambio.", "牡牛座は、忍耐と具体的な手入れで大切なものを保つ象徴。安定は変化を支える土台にもなります。", "황소자리는 인내와 구체적인 돌봄으로 소중한 것을 유지하는 상징이에요. 안정감은 변화를 돕는 바탕이 되기도 해요."],
    example: ["You make a simple weekly routine that protects rest, while leaving one evening free for something new.", "安排一个照顾休息的每周习惯，同时留一晚尝试新事物。", "Creas una rutina semanal que cuida el descanso y dejas una tarde libre para probar algo nuevo.", "休息を守る週の習慣を作りながら、新しいことのために一晩空けておく。", "휴식을 지키는 주간 습관을 만들면서 새로운 일을 위한 저녁 한 번은 비워 둬요."],
    question: ["Which comfort restores you, and which one simply keeps you in place?", "哪一种舒适让你恢复，哪一种只是让你留在原地？", "¿Qué comodidad te renueva y cuál solo te mantiene donde estás?", "回復につながる心地よさと、ただ現状を保つ心地よさの違いは？", "어떤 편안함은 나를 회복시키고, 어떤 편안함은 제자리에 머물게 하나요?"],
    sun: ["Sun in Taurus explores identity through values and consistent effort. Worth need not depend on what you own or produce.", "太阳金牛通过价值与持续投入探索自我，价值不必由拥有或产出来证明。", "El Sol en Tauro explora la identidad mediante valores y constancia. Tu valor no depende de poseer ni producir.", "牡牛座の太陽は、価値観と継続による自己表現。持ち物や成果だけで価値を決める必要はありません。", "황소자리 태양은 가치관과 꾸준함으로 자신을 표현해요. 소유나 생산량만으로 가치를 증명할 필요는 없어요."],
    moon: ["Moon in Taurus associates emotional comfort with reliability, familiar rhythms, and attention to the senses.", "月亮金牛把情绪上的安稳，与可靠的关系、熟悉的节奏和感官照顾联系起来。", "La Luna en Tauro relaciona el bienestar emocional con lo fiable, los ritmos conocidos y el cuidado sensorial.", "牡牛座の月は、信頼できる関係や慣れたリズム、五感への配慮を安心のテーマにします。", "황소자리 달은 신뢰, 익숙한 리듬, 감각을 돌보는 일을 정서적 편안함의 주제로 삼아요."],
    rising: ["Taurus rising suggests meeting new situations at a considered pace, noticing what feels workable and grounded.", "金牛上升象征以审慎的节奏面对新情境，留意什么踏实而可行。", "El ascendente Tauro sugiere acercarte con calma a lo nuevo y observar qué resulta viable y concreto.", "牡牛座のアセンダントは、落ち着いたペースで新しい場に入り、実際に続けられることを見つめます。", "황소자리 상승점은 차분한 속도로 새로운 상황에 들어가며 현실적으로 가능한 것을 살피는 방식이에요."],
  },
  gemini: {
    theme: ["Follow a useful question", "跟随一个有用的问题", "Seguir una pregunta útil", "問いから広げる", "좋은 질문을 따라가기"],
    description: ["Gemini symbolizes curiosity, exchange, and seeing more than one side. Gathering possibilities becomes useful when attention eventually chooses a thread to follow.", "双子座象征好奇、交流与多种视角。收集可能性之后，也可以选择一条线索继续深入。", "Géminis simboliza curiosidad, intercambio y varias perspectivas. Reunir posibilidades ayuda cuando eliges un hilo que seguir.", "双子座は、好奇心と対話、多面的な見方の象徴。可能性を集めたら、一つの糸をたどる時間も大切です。", "쌍둥이자리는 호기심, 대화, 다양한 관점을 상징해요. 가능성을 모은 뒤에는 한 가지 실마리를 따라가 보는 것도 좋아요."],
    example: ["You ask a friend how they reached a different opinion, then summarize what you understood before replying.", "询问朋友为何有不同意见，回应之前先复述你理解到的重点。", "Preguntas cómo llegó alguien a una opinión distinta y resumes lo que entendiste antes de responder.", "違う意見になった理由を友人に聞き、返答する前に理解した内容を確かめる。", "친구가 다른 생각을 하게 된 이유를 묻고, 답하기 전에 이해한 내용을 정리해 봐요."],
    question: ["Which conversation needs more listening, and which question deserves a deeper answer?", "哪一段对话需要多听一点，哪个问题值得再深入？", "¿Qué conversación necesita más escucha y qué pregunta merece profundizar?", "もっと聞きたい会話と、深く考えたい問いは何でしょう？", "어떤 대화에는 더 많은 경청이, 어떤 질문에는 더 깊은 답이 필요한가요?"],
    sun: ["Sun in Gemini explores identity through learning and language, without needing a final label for every part of yourself.", "太阳双子通过学习与语言探索自我，不必急着为每个面向定下标签。", "El Sol en Géminis explora la identidad aprendiendo y conversando, sin exigir una etiqueta definitiva para todo.", "双子座の太陽は、学びと言葉を通じた自己表現。自分のすべてに固定した名前を付けなくても大丈夫です。", "쌍둥이자리 태양은 배움과 언어로 자신을 탐색해요. 모든 면에 확정된 이름을 붙일 필요는 없어요."],
    moon: ["Moon in Gemini connects feelings with words and perspective. Naming a feeling can help without explaining it away.", "月亮双子把感受与语言、视角联系起来。说出感受，不必把感受解释到消失。", "La Luna en Géminis conecta emoción y palabras. Nombrar lo que sientes ayuda sin tener que justificarlo todo.", "双子座の月は、感情と言葉や視点を結びます。気持ちに名前を付けても、説明だけで片づけなくて構いません。", "쌍둥이자리 달은 감정과 말, 관점을 연결해요. 감정을 이름 붙이되 설명만으로 지우지는 않아도 돼요."],
    rising: ["Gemini rising describes a curious, responsive approach: asking questions before deciding what a new setting means.", "双子上升象征好奇而灵活的接触方式，先提问，再理解一个新的环境。", "El ascendente Géminis describe una actitud curiosa y receptiva: preguntar antes de decidir qué significa un entorno nuevo.", "双子座のアセンダントは、問いかけながら新しい場を知ろうとする、好奇心豊かな姿勢です。", "쌍둥이자리 상승점은 질문을 통해 새로운 환경을 알아가는 호기심 있고 유연한 접근이에요."],
  },
  cancer: {
    theme: ["Care with a boundary", "有关怀，也有界限", "Cuidar con límites", "境界のある思いやり", "경계를 지키며 돌보기"],
    description: ["Cancer symbolizes belonging, memory, and protective care. Connection grows when care includes your own needs rather than assuming responsibility for everyone's feelings.", "巨蟹座象征归属、记忆与保护。照顾也包括自己的需要，不必为所有人的感受负责。", "Cáncer simboliza pertenencia, memoria y protección. Cuidar también incluye tus necesidades, sin asumir las emociones de todo el mundo.", "蟹座は、居場所と記憶、守る気持ちの象徴。全員の感情を引き受けず、自分の必要もケアに含めましょう。", "게자리는 소속감, 기억, 보호하는 마음을 상징해요. 모두의 감정을 책임지지 않아도 자신의 필요까지 돌볼 수 있어요."],
    example: ["You offer a friend a listening ear and honestly name how much time you have tonight.", "愿意听朋友说话，也坦诚说明今晚自己有多少时间。", "Escuchas a una amistad y dices con sinceridad cuánto tiempo puedes dedicarle esta noche.", "友人の話を聞きながら、今夜使える時間を正直に伝える。", "친구의 이야기를 들어 주면서 오늘 저녁 내게 얼마나 시간이 있는지도 솔직히 말해요."],
    question: ["What would help you feel at home without asking you to stay exactly the same?", "什么能给你归属感，又不要求你永远保持原样？", "¿Qué te haría sentir en casa sin pedirte que nunca cambies?", "変わっていく自分も受け止められる居場所とは？", "변하지 말라고 요구하지 않으면서도 집처럼 편안하게 해 주는 것은 무엇인가요?"],
    sun: ["Sun in Cancer explores identity through meaningful bonds and care, while allowing belonging to evolve.", "太阳巨蟹通过有意义的连结与照顾探索自我，也允许归属的方式改变。", "El Sol en Cáncer explora la identidad mediante vínculos y cuidados, dejando que la pertenencia evolucione.", "蟹座の太陽は、大切な絆やケアによる自己表現。居場所の形は変化しても構いません。", "게자리 태양은 소중한 관계와 돌봄으로 자신을 표현하며 소속의 방식이 달라질 여지도 남겨요."],
    moon: ["Moon in Cancer emphasizes emotional familiarity and responsiveness. Feeling deeply does not require absorbing every mood around you.", "月亮巨蟹强调熟悉感与情绪回应。感受很深，也不必吸收周围所有情绪。", "La Luna en Cáncer destaca la familiaridad y la sensibilidad. Sentir profundamente no exige absorber cada emoción ajena.", "蟹座の月は、親しみや感情への応答を重視します。深く感じることと、周囲の気分をすべて抱えることは別です。", "게자리 달은 익숙함과 감정에 대한 반응을 강조해요. 깊이 느끼더라도 주변의 모든 기분을 떠안을 필요는 없어요."],
    rising: ["Cancer rising suggests reading a new environment for trust and comfort before choosing how much to reveal.", "巨蟹上升象征先感受新环境里的信任与舒适，再决定表达多少自己。", "El ascendente Cáncer sugiere observar la confianza y comodidad de un entorno antes de decidir cuánto mostrar.", "蟹座のアセンダントは、場の安心感や信頼を確かめてから、自分をどこまで開くか選ぶ姿勢です。", "게자리 상승점은 새로운 환경의 신뢰와 편안함을 살핀 뒤 자신을 얼마나 드러낼지 정하는 방식이에요."],
  },
  leo: {
    theme: ["Let expression be generous", "让表达带着慷慨", "Expresarte con generosidad", "表現に寛大さを", "너그럽게 표현하기"],
    description: ["Leo symbolizes creative presence, warmth, and the wish to contribute something unmistakably your own. Recognition feels richer when it is shared rather than constantly pursued.", "狮子座象征创意、温暖与独特的表达。被看见，也可以是彼此照亮，而不是不断追逐掌声。", "Leo simboliza presencia creativa, calidez y una aportación propia. El reconocimiento se enriquece cuando se comparte, no solo se persigue.", "獅子座は、創造的な存在感と温かさ、自分らしい表現の象徴。注目を追うだけでなく、光を分け合えます。", "사자자리는 창의적인 존재감, 따뜻함, 고유한 표현을 상징해요. 인정은 끊임없이 좇기보다 서로 나눌 때 더 풍성해질 수 있어요."],
    example: ["You share something you made, then make space for a quieter person's contribution too.", "分享自己的创作，也为比较安静的人的贡献留出位置。", "Compartes algo que creaste y das espacio también a la aportación de una persona más reservada.", "作ったものを見せながら、控えめな人の貢献にも目を向ける。", "내가 만든 것을 나누면서 조용한 사람의 기여에도 자리를 내어 줘요."],
    question: ["What would you enjoy creating even if nobody were keeping score?", "如果没有人评分，你仍然想创作什么？", "¿Qué disfrutarías creando aunque nadie llevara la cuenta?", "誰も評価しなくても、作ることを楽しめるものは？", "아무도 점수를 매기지 않아도 즐겁게 만들고 싶은 것은 무엇인가요?"],
    sun: ["Sun in Leo explores identity through heartfelt expression and authorship. Being seen can begin with showing what matters to you.", "太阳狮子通过真诚表达与创作探索自我。被看见，可以从表达自己重视的事开始。", "El Sol en Leo explora la identidad mediante una expresión propia y sincera. Mostrar lo que te importa puede ser un comienzo.", "獅子座の太陽は、心のこもった表現や創作がテーマ。大切なものを見せることから始められます。", "사자자리 태양은 진심 어린 표현과 창작을 통해 자신을 탐색해요. 소중하게 여기는 것을 보여 주는 일부터 시작할 수 있어요."],
    moon: ["Moon in Leo links emotional nourishment with warmth, play, and sincere appreciation rather than constant applause.", "月亮狮子把情绪滋养与温暖、玩心和真诚欣赏联系起来，而不只是掌声。", "La Luna en Leo relaciona el cuidado emocional con calidez, juego y aprecio sincero, más que con aplausos constantes.", "獅子座の月は、温かさや遊び心、心からの感謝を心の栄養とする象徴です。", "사자자리 달은 끊임없는 박수보다 따뜻함, 놀이, 진심 어린 인정을 정서적 양분으로 연결해요."],
    rising: ["Leo rising describes a visible, expressive way of entering a room; quiet confidence can carry it just as well as exuberance.", "狮子上升描述鲜明而有表现力的登场方式，安静的自信也可以承载这份力量。", "El ascendente Leo describe una presencia expresiva; la confianza tranquila puede sostenerla tanto como el entusiasmo.", "獅子座のアセンダントは、印象に残る表現豊かな姿勢。華やかさだけでなく、静かな自信にも表れます。", "사자자리 상승점은 표현력이 있고 눈에 띄는 접근이에요. 활기뿐 아니라 조용한 자신감으로도 나타날 수 있어요."],
  },
  virgo: {
    theme: ["Improve what is useful", "改善真正有用的部分", "Mejorar lo que sirve", "役立つところを整える", "도움이 되는 부분 다듬기"],
    description: ["Virgo symbolizes discernment, practice, and practical care. Noticing a detail is most helpful when it serves life, rather than becoming a demand for flawlessness.", "处女座象征辨识、练习与实际照顾。细节用来支持生活，不必变成对完美的要求。", "Virgo simboliza discernimiento, práctica y cuidado concreto. Atender al detalle ayuda cuando sirve a la vida, no a la perfección.", "乙女座は、見極めと練習、具体的なケアの象徴。細部は完璧を求めるためではなく、暮らしを助けるためにあります。", "처녀자리는 분별, 연습, 실질적인 돌봄을 상징해요. 세부 사항은 완벽함을 요구하기보다 삶을 돕는 데 쓰일 수 있어요."],
    example: ["You simplify one confusing step in a routine instead of trying to redesign your entire week.", "把日常流程里一个混乱的步骤理顺，而不是一次重排整周生活。", "Simplificas un paso confuso de una rutina en lugar de intentar rediseñar toda la semana.", "一週間を全部変えようとせず、習慣の中の分かりにくい一段階を整える。", "일주일 전체를 바꾸려 하기보다 일상에서 헷갈리는 한 단계를 간단하게 정리해요."],
    question: ["What is one useful improvement you can make without turning yourself into a project?", "不把自己当成待修理的项目，你可以做哪一个有用的小改善？", "¿Qué mejora útil puedes hacer sin convertirte en un proyecto que corregir?", "自分を直すべき課題にせずに、できる小さな工夫は？", "나 자신을 고쳐야 할 프로젝트로 만들지 않고 할 수 있는 작은 개선은 무엇인가요?"],
    sun: ["Sun in Virgo explores identity through craft and usefulness. Contributing does not require being indispensable.", "太阳处女通过技艺与实用价值探索自我，有贡献不等于必须不可替代。", "El Sol en Virgo explora la identidad mediante oficio y utilidad. Aportar no exige volverte indispensable.", "乙女座の太陽は、技術や役立つことによる自己表現。貢献するために不可欠な人である必要はありません。", "처녀자리 태양은 기술과 쓸모를 통해 자신을 표현해요. 기여하기 위해 반드시 없어서는 안 될 사람이 될 필요는 없어요."],
    moon: ["Moon in Virgo connects emotional steadiness with manageable routines and thoughtful details; feelings need not be solved immediately.", "月亮处女把情绪稳定与可掌握的习惯、体贴的细节联系起来；感受不必立刻解决。", "La Luna en Virgo vincula la calma con rutinas manejables y detalles atentos; una emoción no necesita resolverse al instante.", "乙女座の月は、扱いやすい習慣や心配りを安心につなげます。感情をすぐ解決しなくても構いません。", "처녀자리 달은 감당할 수 있는 습관과 세심한 배려를 안정감과 연결해요. 감정은 즉시 해결하지 않아도 돼요."],
    rising: ["Virgo rising suggests observing how things work before engaging, with attention that can become care rather than criticism.", "处女上升象征先观察运作方式，再参与其中；细心可以成为照顾，而不只是挑错。", "El ascendente Virgo sugiere observar cómo funcionan las cosas; esa atención puede convertirse en cuidado, no solo en crítica.", "乙女座のアセンダントは、仕組みを見てから関わる姿勢。観察力は批判だけでなく、ケアにも使えます。", "처녀자리 상승점은 일이 어떻게 돌아가는지 관찰한 뒤 참여하는 방식이에요. 주의 깊음은 비판보다 돌봄으로 이어질 수 있어요."],
  },
  libra: {
    theme: ["Find balance in dialogue", "在对话中寻找平衡", "Buscar equilibrio dialogando", "対話で釣り合いを探す", "대화 속에서 균형 찾기"],
    description: ["Libra symbolizes relating, perspective, and fair exchange. Balance is something people negotiate; it need not mean avoiding disagreement or making every choice equally pleasing.", "天秤座象征关系、视角与公平的交换。平衡需要协商，不代表避免分歧或让每个选择都讨好所有人。", "Libra simboliza relación, perspectiva e intercambio justo. El equilibrio se negocia; no exige evitar diferencias ni complacer a todo el mundo.", "天秤座は、関係と視点、公平なやり取りの象徴。調和は話し合うもので、意見の違いを消すことではありません。", "천칭자리는 관계, 관점, 공정한 교환을 상징해요. 균형은 함께 조율하는 것이며 의견 차이를 피하거나 모두를 만족시키는 일은 아니에요."],
    example: ["You suggest a compromise after clearly stating your own preference, rather than silently giving it up.", "先清楚表达自己的偏好，再提出折中方案，而不是默默放弃。", "Propones un acuerdo después de expresar tu preferencia, en vez de renunciar a ella en silencio.", "自分の希望を黙って引っ込めず、まず伝えたうえで折り合いを提案する。", "내 취향을 조용히 포기하기보다 먼저 분명히 말한 뒤 절충안을 제안해요."],
    question: ["Where would a clear preference create more honesty than another polite agreement?", "在哪里，清楚表达偏好比再一次礼貌同意更诚实？", "¿Dónde sería más honesto expresar una preferencia que volver a asentir por cortesía?", "丁寧に同意するより、自分の希望を伝えた方が誠実な場面は？", "예의상 또 동의하기보다 선호를 분명히 밝히는 편이 더 솔직한 곳은 어디인가요?"],
    sun: ["Sun in Libra explores identity through partnership and perspective while learning that your own position belongs in the conversation.", "太阳天秤通过合作与视角探索自我，同时让自己的立场也进入对话。", "El Sol en Libra explora la identidad mediante vínculos y perspectivas, incluyendo tu propia postura en la conversación.", "天秤座の太陽は、関係や多様な視点による自己表現。自分の立場も対話の一部です。", "천칭자리 태양은 관계와 다양한 관점을 통해 자신을 탐색해요. 자신의 입장도 대화에 포함될 수 있어요."],
    moon: ["Moon in Libra associates emotional ease with reciprocity and thoughtful exchange; disagreement can coexist with care.", "月亮天秤把情绪舒适与互惠、体贴的交流联系起来；不同意见可以与关心并存。", "La Luna en Libra asocia el bienestar emocional con reciprocidad y diálogo atento; discrepar también puede ser cuidar.", "天秤座の月は、互いを思うやり取りを安心につなげます。意見の違いとケアは両立します。", "천칭자리 달은 주고받는 배려와 대화를 편안함과 연결해요. 의견이 달라도 서로를 아낄 수 있어요."],
    rising: ["Libra rising describes an approach that notices relationships and atmosphere, without requiring you to manage everyone's impression.", "天秤上升描述留意关系与氛围的方式，不要求你负责每个人的感受与印象。", "El ascendente Libra describe atención a los vínculos y al ambiente, sin obligarte a gestionar la impresión de todos.", "天秤座のアセンダントは、関係や場の雰囲気を捉える姿勢。全員の印象を管理しなくても大丈夫です。", "천칭자리 상승점은 관계와 분위기를 살피는 접근이에요. 모든 사람에게 어떻게 보이는지 관리할 필요는 없어요."],
  },
  scorpio: {
    theme: ["Let trust earn its depth", "让信任慢慢生根", "Dar profundidad a la confianza", "信頼を深める時間", "신뢰를 천천히 깊게 하기"],
    description: ["Scorpio symbolizes depth, privacy, and the exchanges that change us. Intensity becomes more workable when trust is built through clear consent rather than tests or assumptions.", "天蝎座象征深度、隐私与带来改变的交流。信任来自清楚的同意，不必靠试探或猜测建立。", "Escorpio simboliza profundidad, intimidad e intercambios que nos transforman. La confianza se construye con consentimiento claro, no con pruebas ni suposiciones.", "蠍座は、深さとプライバシー、変化をもたらす交流の象徴。信頼は試すことより、明確な同意から育ちます。", "전갈자리는 깊이, 사생활, 변화를 가져오는 교류를 상징해요. 신뢰는 상대를 시험하거나 추측하기보다 명확한 동의로 쌓을 수 있어요."],
    example: ["Before discussing something personal, you ask whether the other person has space for that conversation.", "在谈较私密的事情之前，先询问对方是否有空间聊这个话题。", "Antes de hablar de algo íntimo, preguntas si la otra persona tiene espacio para esa conversación.", "個人的な話をする前に、その会話をする余裕があるか相手に尋ねる。", "사적인 이야기를 꺼내기 전에 상대에게 그 대화를 나눌 여유가 있는지 물어봐요."],
    question: ["What boundary would make openness feel more trustworthy rather than less intimate?", "哪一个界限能让坦诚更值得信任，而不是更疏远？", "¿Qué límite haría que abrirte resultara más fiable, no menos cercano?", "距離を遠ざけず、安心して開けるようになる境界は？", "친밀함을 줄이지 않으면서 마음을 더 믿고 열게 해 줄 경계는 무엇인가요?"],
    sun: ["Sun in Scorpio explores identity through depth and meaningful change. You can be sincere without revealing everything.", "太阳天蝎通过深度与有意义的改变探索自我，真诚不等于公开一切。", "El Sol en Escorpio explora la identidad mediante profundidad y cambio. La sinceridad no exige revelarlo todo.", "蠍座の太陽は、深く向き合うことや変化による自己表現。すべてを明かさなくても誠実でいられます。", "전갈자리 태양은 깊이와 의미 있는 변화를 통해 자신을 탐색해요. 모든 것을 공개하지 않아도 진실할 수 있어요."],
    moon: ["Moon in Scorpio associates feelings with privacy and depth. Trust can grow in small disclosures at a pace you choose.", "月亮天蝎把感受与隐私、深度联系起来。你可以选择节奏，让信任从小小的分享开始。", "La Luna en Escorpio vincula la emoción con intimidad y profundidad. Puedes construir confianza compartiendo poco a poco, a tu ritmo.", "蠍座の月は、感情を深さやプライバシーと結びます。選んだペースで少しずつ分かち合うことも信頼です。", "전갈자리 달은 감정을 사생활과 깊이로 연결해요. 내가 정한 속도로 조금씩 나누며 신뢰를 키울 수 있어요."],
    rising: ["Scorpio rising suggests meeting a new situation with focused observation and a deliberate choice about access.", "天蝎上升象征专注观察新情境，再审慎决定让他人靠近的程度。", "El ascendente Escorpio sugiere observar con atención lo nuevo y decidir conscientemente cuánto acceso dar.", "蠍座のアセンダントは、新しい場を集中して観察し、どこまで近づくかを意識して選ぶ姿勢です。", "전갈자리 상승점은 새로운 상황을 집중해 관찰하고 얼마나 가까이 다가갈지 신중히 선택하는 방식이에요."],
  },
  sagittarius: {
    theme: ["Explore beyond the first answer", "走到第一个答案之外", "Explorar más allá de la primera respuesta", "最初の答えの先へ", "첫 답 너머로 탐색하기"],
    description: ["Sagittarius symbolizes exploration, meaning, and a wider horizon. Confidence grows more thoughtful when a compelling belief can still be questioned by experience.", "射手座象征探索、意义与更宽的视野。充满信心的想法，也可以接受经验带来的提问。", "Sagitario simboliza exploración, sentido y horizontes amplios. La confianza gana profundidad cuando la experiencia puede cuestionar una creencia.", "射手座は、探求と意味、広い視野の象徴。信じる考えにも、経験からの問いを受け入れる余地があります。", "사수자리는 탐험, 의미, 넓은 시야를 상징해요. 확신하는 생각도 경험이 던지는 질문을 받아들일 수 있어요."],
    example: ["You try an unfamiliar class and let one surprising detail change what you thought you already knew.", "尝试一门陌生的课程，让一个意外的细节改变原本以为懂了的事。", "Pruebas una clase desconocida y dejas que un detalle sorprendente cambie algo que creías saber.", "初めての講座に参加し、意外な細部から「知っているつもり」を見直す。", "낯선 수업을 들어 보고, 뜻밖의 세부 내용이 이미 안다고 생각했던 것을 바꾸게 해 봐요."],
    question: ["Which belief becomes more useful when you leave room to revise it?", "哪一个信念，在允许修正之后会更有用？", "¿Qué creencia sería más útil si dejaras espacio para revisarla?", "見直す余地を残すことで、より役立つようになる考えは？", "수정할 여지를 남길 때 더 도움이 되는 믿음은 무엇인가요?"],
    sun: ["Sun in Sagittarius explores identity through discovery and meaning, without needing every experience to become a grand lesson.", "太阳射手通过发现与意义探索自我，不必让每个经历都成为宏大的道理。", "El Sol en Sagitario explora la identidad mediante descubrimiento y sentido, sin convertir cada experiencia en una gran lección.", "射手座の太陽は、発見と意味を通じた自己表現。すべての経験を大きな教訓にしなくても構いません。", "사수자리 태양은 발견과 의미로 자신을 탐색해요. 모든 경험을 거대한 교훈으로 만들 필요는 없어요."],
    moon: ["Moon in Sagittarius connects emotional space with possibility and perspective. Hope can include the feeling that is here now.", "月亮射手把情绪空间与可能性、视角联系起来。有希望，也能容纳当下的感受。", "La Luna en Sagitario conecta el espacio emocional con posibilidades y perspectiva. La esperanza puede incluir lo que sientes ahora.", "射手座の月は、可能性や広い視点を心の余白につなげます。希望と今の気持ちは一緒に持てます。", "사수자리 달은 가능성과 넓은 관점을 마음의 여유와 연결해요. 희망을 품으면서 지금의 감정도 받아들일 수 있어요."],
    rising: ["Sagittarius rising describes an open, exploratory entry into new settings, with curiosity that benefits from checking assumptions.", "射手上升描述开放而探索式的进入方式，好奇也可以搭配对假设的检验。", "El ascendente Sagitario describe una entrada abierta y exploradora; la curiosidad se enriquece al revisar las suposiciones.", "射手座のアセンダントは、新しい場へ開かれた探求心で入る姿勢。前提を確かめることも好奇心の一部です。", "사수자리 상승점은 열린 탐구심으로 새로운 상황에 다가가는 방식이에요. 가정을 확인하는 일도 호기심을 풍부하게 해요."],
  },
  capricorn: {
    theme: ["Build something sustainable", "建立能够持续的事物", "Construir algo sostenible", "続けられる形を作る", "지속할 수 있는 것 만들기"],
    description: ["Capricorn symbolizes structure, responsibility, and effort across time. Ambition is more sustainable when rest and support belong inside the plan, not after its completion.", "摩羯座象征结构、责任与长期投入。休息和支持可以放进计划里，而不是等成功后才允许。", "Capricornio simboliza estructura, responsabilidad y esfuerzo sostenido. La ambición es más sostenible si descanso y apoyo forman parte del plan.", "山羊座は、構造と責任、時間をかける努力の象徴。休息や支えは、完成後のご褒美ではなく計画の一部です。", "염소자리는 구조, 책임, 시간을 들이는 노력을 상징해요. 휴식과 도움을 완성 뒤의 보상이 아니라 계획 안에 넣어 보세요."],
    example: ["You break a distant goal into one realistic step and agree on when to stop working for the day.", "把远方的目标拆成一个实际步骤，也设定今天停止工作的时间。", "Divides una meta lejana en un paso realista y decides a qué hora terminar de trabajar hoy.", "遠い目標を現実的な一歩に分け、今日の作業を終える時間も決める。", "먼 목표를 현실적인 한 단계로 나누고, 오늘 일을 마칠 시간도 정해요."],
    question: ["Which responsibility is truly yours, and which one could be shared?", "哪一份责任确实属于你，哪一份可以共同承担？", "¿Qué responsabilidad es realmente tuya y cuál podría compartirse?", "本当に自分が担う責任と、分かち合える責任は？", "정말 내 책임인 것은 무엇이고, 함께 나눌 수 있는 것은 무엇인가요?"],
    sun: ["Sun in Capricorn explores identity through commitment and earned capability. Your worth can remain intact on an unproductive day.", "太阳摩羯通过承诺与积累的能力探索自我。没有产出的一天，也不减少你的价值。", "El Sol en Capricornio explora la identidad con compromiso y capacidad adquirida. Un día sin producir no reduce tu valor.", "山羊座の太陽は、取り組み続けることや身につけた力がテーマ。成果のない日も、自分の価値は変わりません。", "염소자리 태양은 책임 있는 노력과 쌓아 온 능력으로 자신을 탐색해요. 성과가 없는 날에도 나의 가치는 그대로예요."],
    moon: ["Moon in Capricorn associates emotional steadiness with dependable structure. Asking for support can be a responsible choice too.", "月亮摩羯把情绪安稳与可靠的结构联系起来，寻求支持也可以是负责的选择。", "La Luna en Capricornio asocia la calma emocional con estructuras fiables. Pedir apoyo también puede ser responsable.", "山羊座の月は、頼れる仕組みを安心につなげます。助けを求めることも、責任ある選択になり得ます。", "염소자리 달은 믿을 만한 구조를 정서적 안정과 연결해요. 도움을 요청하는 것도 책임 있는 선택일 수 있어요."],
    rising: ["Capricorn rising suggests a measured approach to unfamiliar settings, learning the structure before choosing a contribution.", "摩羯上升象征有分寸地面对新情境，先理解结构，再选择自己的贡献方式。", "El ascendente Capricornio sugiere acercarte con mesura, comprendiendo la estructura antes de elegir tu aportación.", "山羊座のアセンダントは、場の仕組みを理解してから関わり方を選ぶ、慎重な姿勢です。", "염소자리 상승점은 새로운 환경의 구조를 이해한 뒤 자신의 기여 방식을 선택하는 신중한 접근이에요."],
  },
  aquarius: {
    theme: ["Make difference useful", "让不同产生意义", "Dar sentido a la diferencia", "違いを役立てる", "다름을 도움이 되게 하기"],
    description: ["Aquarius symbolizes independent thought, shared systems, and alternatives to the usual way. A big idea becomes more humane when it stays curious about individual lives.", "水瓶座象征独立思考、共同系统与不同的可能。宏观想法，也可以持续关心每个人的真实生活。", "Acuario simboliza pensamiento independiente, sistemas compartidos y alternativas. Una gran idea se vuelve más humana al escuchar vidas concretas.", "水瓶座は、独立した思考や共同の仕組み、別の可能性の象徴。大きな考えにも、一人ひとりの暮らしへの関心を。", "물병자리는 독립적인 생각, 함께 쓰는 체계, 새로운 대안을 상징해요. 큰 아이디어에 개개인의 삶을 향한 관심을 더해 보세요."],
    example: ["You propose a fairer group routine, then ask the people affected what would actually help them.", "提出更公平的团队做法，再询问受影响的人什么才真正有帮助。", "Propones una dinámica de grupo más justa y preguntas a las personas afectadas qué les ayudaría de verdad.", "より公平なグループの仕組みを提案し、関わる人に何が助けになるか聞いてみる。", "더 공정한 모임의 방식을 제안한 뒤, 영향을 받는 사람들에게 실제로 무엇이 도움이 될지 물어봐요."],
    question: ["How can you honor your difference while staying present with other people's experience?", "怎样保留自己的不同，也贴近别人的经验？", "¿Cómo puedes honrar tu diferencia sin perder contacto con la experiencia ajena?", "自分の違いを大切にしながら、相手の経験にも寄り添うには？", "내 다름을 존중하면서 다른 사람의 경험 곁에도 머무르려면 어떻게 할 수 있나요?"],
    sun: ["Sun in Aquarius explores identity through independent ideas and collective possibility. Belonging does not require being conventional or exceptional.", "太阳水瓶通过独立想法与共同可能探索自我。归属不要求你普通，也不要求你特别。", "El Sol en Acuario explora la identidad con ideas propias y posibilidades colectivas. Pertenecer no exige ser convencional ni excepcional.", "水瓶座の太陽は、独自の考えやみんなの可能性がテーマ。所属するために、普通でも特別でもある必要はありません。", "물병자리 태양은 독립적인 생각과 공동의 가능성으로 자신을 탐색해요. 소속되기 위해 평범하거나 특별할 필요는 없어요."],
    moon: ["Moon in Aquarius links emotional perspective with space and friendship. Understanding a feeling can sit alongside feeling it.", "月亮水瓶把情绪视角与空间、友谊联系起来。理解感受与实际感受，可以同时存在。", "La Luna en Acuario conecta la perspectiva emocional con espacio y amistad. Comprender una emoción puede acompañar a sentirla.", "水瓶座の月は、距離や友情を感情の視点につなげます。理解することと、実際に感じることは両立します。", "물병자리 달은 여유와 우정을 감정에 대한 관점과 연결해요. 감정을 이해하는 것과 느끼는 것은 함께할 수 있어요."],
    rising: ["Aquarius rising describes an observant, independent approach that notices alternatives before accepting the usual script.", "水瓶上升描述独立而善于观察的方式，在接受惯例之前，先看见其他可能。", "El ascendente Acuario describe una mirada independiente que observa alternativas antes de aceptar el guion habitual.", "水瓶座のアセンダントは、いつものやり方を受け入れる前に、別の選択肢を見つける独立した姿勢です。", "물병자리 상승점은 익숙한 각본을 받아들이기 전에 다른 선택지를 발견하는 독립적이고 관찰력 있는 방식이에요."],
  },
  pisces: {
    theme: ["Give imagination a container", "为想象留一个容器", "Dar un cauce a la imaginación", "想像力に器を", "상상력을 담을 그릇"],
    description: ["Pisces symbolizes imagination, receptivity, and the connections that words do not fully hold. Sensitivity becomes easier to work with when boundaries offer it a shape.", "双鱼座象征想象、感受力与语言难以完全承载的连结。界限可以为敏感提供形状，让它更容易安放。", "Piscis simboliza imaginación, receptividad y vínculos que las palabras no abarcan. Los límites pueden dar una forma útil a la sensibilidad.", "魚座は、想像力と受容性、言葉だけでは捉えきれないつながりの象徴。境界は繊細さを支える器になります。", "물고기자리는 상상력, 수용성, 말로 다 담을 수 없는 연결을 상징해요. 경계는 섬세함을 담아 주는 그릇이 될 수 있어요."],
    example: ["You turn a difficult-to-name feeling into a sketch, then choose one concrete thing you need today.", "把难以命名的感受画下来，再选出今天一个具体的需要。", "Dibujas una emoción difícil de nombrar y después eliges algo concreto que necesitas hoy.", "言葉にしにくい気持ちを絵にしてから、今日必要な具体的なものを一つ選ぶ。", "이름 붙이기 어려운 감정을 그림으로 표현한 뒤, 오늘 필요한 구체적인 것 하나를 골라요."],
    question: ["What helps you stay compassionate without losing track of your own limits?", "什么能让你保有关怀，又不忘记自己的界限？", "¿Qué te ayuda a mantener la compasión sin perder de vista tus límites?", "自分の限界を見失わずに、思いやりを保つ助けになることは？", "내 한계를 놓치지 않으면서 다정함을 유지하도록 돕는 것은 무엇인가요?"],
    sun: ["Sun in Pisces explores identity through imagination and connection. A flexible sense of self can still include a clear no.", "太阳双鱼通过想象与连结探索自我。柔软的自我感，也能包含清楚的拒绝。", "El Sol en Piscis explora la identidad mediante imaginación y conexión. Una identidad flexible también puede decir no con claridad.", "魚座の太陽は、想像やつながりを通じた自己表現。柔軟な自分のあり方にも、明確な「いいえ」を含められます。", "물고기자리 태양은 상상력과 연결로 자신을 탐색해요. 유연한 자아 안에도 분명한 거절이 있을 수 있어요."],
    moon: ["Moon in Pisces associates emotional life with receptivity and imagination. Quiet time can help distinguish your feelings from the atmosphere around you.", "月亮双鱼把情绪生活与感受力、想象联系起来。安静的时间有助于分辨自己的感受与周围氛围。", "La Luna en Piscis vincula la emoción con receptividad e imaginación. Un rato de calma ayuda a distinguir lo propio del ambiente.", "魚座の月は、受容性や想像力を感情と結びます。静かな時間は、自分の気持ちと周囲の空気を分ける助けになります。", "물고기자리 달은 수용성과 상상력을 감정과 연결해요. 조용한 시간은 내 감정과 주변 분위기를 구분하는 데 도움이 될 수 있어요."],
    rising: ["Pisces rising suggests an intuitive, adaptable entry into a new setting; taking time to orient yourself can make that openness easier.", "双鱼上升象征凭感受、灵活地进入新情境；先给自己定位的时间，能让开放更自在。", "El ascendente Piscis sugiere una entrada intuitiva y adaptable; darte tiempo para orientarte puede sostener esa apertura.", "魚座のアセンダントは、感覚を受け取りながら柔軟に新しい場へ入る姿勢。自分の位置を確かめる時間も大切です。", "물고기자리 상승점은 직관적이고 유연하게 새 환경에 다가가는 방식이에요. 내 위치를 파악할 시간을 주면 그 열린 마음도 편안해질 수 있어요."],
  },
};

export function signArticle(sign: ZodiacSign, language: HintLanguage): SignArticle {
  const index = SIGN_ORDER.indexOf(sign);
  const translated = Object.fromEntries(Object.entries(articles[sign]).map(([key, copy]) => [key, astroText(language, copy)])) as Record<keyof ArticleCopy, string>;
  return { ...translated, element: astroText(language, elements[index % 4]!), modality: astroText(language, modalities[index % 3]!) };
}

const bodies: Record<string, { name: AstroCopy; description: AstroCopy }> = {
  sun: { name: ["Sun", "太阳", "Sol", "太陽", "태양"], description: ["The Sun symbolizes identity, vitality, and conscious expression. Its sign describes one way these themes may be expressed, not your whole personality.", "太阳象征自我、活力与有意识的表达。太阳星座只是这些主题的一种表达方式，不是你的全部性格。", "El Sol simboliza identidad, vitalidad y expresión consciente. Su signo describe una forma de expresar estos temas, no toda tu personalidad.", "太陽は、自己意識や活力、意識的な表現の象徴。その星座だけで、性格のすべてを説明するわけではありません。", "태양은 정체성, 활력, 의식적인 표현을 상징해요. 태양의 별자리는 그 표현 방식 중 하나이며 성격 전체를 뜻하지 않아요."] },
  moon: { name: ["Moon", "月亮", "Luna", "月", "달"], description: ["The Moon symbolizes emotional needs, familiar responses, and what feels nurturing. Its placement invites reflection on care, not a diagnosis of your inner life.", "月亮象征情感需要、熟悉的回应与滋养感。它邀请你思考照顾的方式，不是对内心状态的诊断。", "La Luna simboliza necesidades emocionales, respuestas conocidas y cuidados. Su posición invita a reflexionar, no diagnostica tu vida interior.", "月は、感情の必要や慣れた反応、安心を育むものの象徴。内面を診断するものではなく、ケアを考える入り口です。", "달은 정서적 필요, 익숙한 반응, 돌봄을 상징해요. 내면을 진단하기보다 자신을 돌보는 방식을 돌아보는 계기가 될 수 있어요."] },
  rising: { name: ["Ascendant", "上升", "Ascendente", "アセンダント", "상승점"], description: ["The Ascendant is the zodiac point rising on the eastern horizon at birth, not a planet. It describes an approach to the world and needs accurate birth time and place.", "上升是出生时东方地平线上的黄道交点，不是行星。它象征接触世界的方式，需要准确的出生时间与地点。", "El ascendente es el punto del zodiaco que aparece en el horizonte oriental al nacer, no un planeta. Requiere hora y lugar precisos.", "アセンダントは出生時の東の地平線と黄道の交点で、惑星ではありません。世界への接し方を表し、正確な出生時刻と場所が必要です。", "상승점은 출생 당시 동쪽 지평선과 황도가 만나는 지점으로, 행성이 아니에요. 세상에 다가가는 방식을 나타내며 정확한 출생 시간과 장소가 필요해요."] },
  mercury: { name: ["Mercury", "水星", "Mercurio", "水星", "수성"], description: ["Mercury symbolizes thinking, learning, and exchanging information. Its sign is a lens for communication style, not a measure of intelligence.", "水星象征思考、学习与信息交流。水星星座帮助理解沟通风格，不衡量智力。", "Mercurio simboliza pensamiento, aprendizaje e intercambio de información. Su signo orienta sobre estilo comunicativo, no mide inteligencia.", "水星は、思考と学び、情報のやり取りの象徴。その星座は伝え方の視点であり、知能の尺度ではありません。", "수성은 사고, 배움, 정보 교환을 상징해요. 별자리는 소통 방식을 살피는 관점이지 지능의 척도는 아니에요."] },
  venus: { name: ["Venus", "金星", "Venus", "金星", "금성"], description: ["Venus symbolizes affection, enjoyment, and what you value. Its placement can prompt questions about relating and taste without deciding whom you should love.", "金星象征亲近、享受与重视的事物。它可以带来关于关系与品味的问题，不决定你应该爱谁。", "Venus simboliza afecto, disfrute y valores. Invita a pensar en vínculos y gustos sin decidir a quién deberías amar.", "金星は、愛情や楽しみ、大切にするものの象徴。関係や好みを考えるきっかけであり、愛する相手を決めるものではありません。", "금성은 애정, 즐거움, 소중히 여기는 것을 상징해요. 관계와 취향을 돌아볼 수 있지만 누구를 사랑해야 하는지 결정하지는 않아요."] },
  mars: { name: ["Mars", "火星", "Marte", "火星", "화성"], description: ["Mars symbolizes action, assertion, and the pursuit of a goal. Its placement offers a way to explore how initiative and boundaries work together.", "火星象征行动、主张与追求目标。它提供一个角度，探索主动与界限如何相互配合。", "Marte simboliza acción, afirmación y búsqueda de objetivos. Su posición permite explorar cómo colaboran iniciativa y límites.", "火星は、行動や自己主張、目標へ向かう力の象徴。主体性と境界の関係を見つめる視点です。", "화성은 행동, 자기주장, 목표를 향한 움직임을 상징해요. 주도성과 경계가 어떻게 함께 작용하는지 탐색하는 관점이에요."] },
  jupiter: { name: ["Jupiter", "木星", "Júpiter", "木星", "목성"], description: ["Jupiter symbolizes growth, meaning, and widening perspective. Expansion can be useful, but the placement does not guarantee luck or success.", "木星象征成长、意义与视野扩展。扩展可以有帮助，但这个配置不保证幸运或成功。", "Júpiter simboliza crecimiento, sentido y amplitud de perspectiva. La expansión puede ayudar, pero no garantiza suerte ni éxito.", "木星は、成長や意味、視野の広がりの象徴。可能性を考える視点であり、幸運や成功を保証しません。", "목성은 성장, 의미, 시야의 확장을 상징해요. 확장이 도움이 될 수 있지만 행운이나 성공을 보장하지는 않아요."] },
  saturn: { name: ["Saturn", "土星", "Saturno", "土星", "토성"], description: ["Saturn symbolizes limits, commitments, and skills developed over time. It invites reflection on support and responsibility, not punishment or inevitable hardship.", "土星象征限制、承诺与长期培养的能力。它邀请你思考支持与责任，不代表惩罚或必然的困难。", "Saturno simboliza límites, compromisos y capacidades cultivadas con tiempo. Invita a pensar en apoyo y responsabilidad, no en castigos inevitables.", "土星は、限界や約束、時間をかけて育つ力の象徴。罰や避けられない苦労ではなく、支えと責任を考えます。", "토성은 한계, 약속, 시간을 들여 기른 능력을 상징해요. 벌이나 피할 수 없는 고난이 아니라 지지와 책임을 돌아보는 주제예요."] },
  uranus: { name: ["Uranus", "天王星", "Urano", "天王星", "천왕성"], description: ["Uranus symbolizes independence and departures from established patterns. Its slow movement makes its sign a shared generational theme, not a uniquely personal signature.", "天王星象征独立与对既有模式的突破。它移动缓慢，所在星座更多是世代共有的主题，并非个人独有的标签。", "Urano simboliza independencia y cambios de patrón. Su movimiento lento hace de su signo un tema generacional compartido, no exclusivamente personal.", "天王星は、独立性や従来の形を離れることの象徴。動きが遅いため、星座は個人だけでなく世代で共有するテーマです。", "천왕성은 독립성과 익숙한 패턴에서 벗어남을 상징해요. 천천히 움직이므로 별자리는 개인만의 특징보다 세대가 공유하는 주제에 가까워요."] },
  neptune: { name: ["Neptune", "海王星", "Neptuno", "海王星", "해왕성"], description: ["Neptune symbolizes imagination, ideals, and blurred boundaries. Its sign is shared across a generation; specific chart connections add context without making intuition infallible.", "海王星象征想象、理想与模糊的界限。星座是世代共有的配置，具体相位可以增加背景，但不让直觉变得绝对正确。", "Neptuno simboliza imaginación, ideales y límites difusos. Su signo es generacional; las conexiones concretas añaden contexto sin volver infalible la intuición.", "海王星は、想像や理想、曖昧な境界の象徴。星座は世代の共有テーマで、具体的な配置も直感の正しさを保証しません。", "해왕성은 상상력, 이상, 흐릿한 경계를 상징해요. 별자리는 세대가 공유하며 구체적인 연결도 직관의 정확함을 보장하지는 않아요."] },
  pluto: { name: ["Pluto", "冥王星", "Plutón", "冥王星", "명왕성"], description: ["Pluto symbolizes power, deep change, and what is difficult to let go of. Its sign is generational; it is not evidence that a crisis must happen.", "冥王星象征力量、深层改变与难以放下的事物。它的星座带有世代性，不是危机必然发生的证据。", "Plutón simboliza poder, cambio profundo y lo difícil de soltar. Su signo es generacional; no demuestra que deba ocurrir una crisis.", "冥王星は、力や深い変化、手放しにくいものの象徴。星座は世代的なもので、危機が起きる証拠ではありません。", "명왕성은 힘, 깊은 변화, 놓기 어려운 것을 상징해요. 별자리는 세대적인 주제이며 위기가 일어난다는 증거는 아니에요."] },
};
function bodyKey(body: string): string {
  const key = body.toLowerCase().replace(/[\s_-]/g, "");
  return key === "asc" || key === "ascendant" ? "rising" : key;
}
export function canonicalBody(body: string): PlanetBody | null {
  const key = bodyKey(body);
  return Object.hasOwn(bodies, key) ? key as PlanetBody : null;
}
export function bodyName(body: string, language: HintLanguage): string { const key = canonicalBody(body); const row = key ? bodies[key] : null; return row ? astroText(language, row.name) : body; }
export function bodyDescription(body: string, language: HintLanguage): string {
  const key = canonicalBody(body);
  const row = key ? bodies[key] : null;
  return astroText(language, row?.description ?? ["This point has no explanation in the current guide.", "当前指南尚未提供这个配置点的说明。", "La guía actual no incluye una explicación de este punto.", "このポイントの説明は、現在のガイドにはありません。", "현재 가이드에는 이 지점에 대한 설명이 없어요."]);
}

const houses: AstroCopy[] = [
  ["House 1 concerns presence and how you enter situations. Read it alongside the Ascendant when available; it does not contain your whole identity.", "第一宫关联自身的呈现与进入情境的方式。上升点已提供时可一起阅读，但它不包含你的全部身份。", "La casa 1 trata de presencia y de cómo entras en situaciones. Léela junto al ascendente cuando esté disponible; no abarca toda tu identidad.", "第1ハウスは、存在の示し方や場への入り方。アセンダントがある場合は併せて読みますが、自己のすべてではありません。", "1하우스는 존재감을 드러내고 상황에 들어가는 방식과 관련돼요. 상승점이 제공되면 함께 읽되, 정체성 전체를 담는 것은 아니에요."],
  ["House 2 concerns personal resources, possessions, and values. It can prompt reflection on enoughness, not predict wealth.", "第二宫关联个人资源、拥有的事物与价值。它可用于思考什么是足够，而不是预测财富。", "La casa 2 trata de recursos propios, posesiones y valores. Invita a pensar qué es suficiente, no predice riqueza.", "第2ハウスは、自分の資源や持ち物、価値観。豊かさを予言するのではなく、十分とは何かを考えます。", "2하우스는 개인의 자원, 소유, 가치관과 관련돼요. 재산을 예측하기보다 충분함의 의미를 돌아볼 수 있어요."],
  ["House 3 concerns everyday communication, early learning, and your nearby environment. Notice how information moves through daily life.", "第三宫关联日常沟通、基础学习与周边环境。可以留意信息在生活中如何传递。", "La casa 3 trata de comunicación cotidiana, aprendizaje inicial y entorno cercano. Observa cómo circula la información en tu día.", "第3ハウスは、日々の会話や初期の学び、身近な環境。暮らしの中の情報の流れに目を向けます。", "3하우스는 일상적인 소통, 기초적인 배움, 가까운 환경과 관련돼요. 하루 속에서 정보가 오가는 방식을 살펴봐요."],
  ["House 4 concerns home, roots, and private foundations. Belonging may be inherited, chosen, or gradually rebuilt.", "第四宫关联家庭、根源与私人的基础。归属可以来自过去，也可以由选择与重建而来。", "La casa 4 trata de hogar, raíces y bases íntimas. La pertenencia puede heredarse, elegirse o reconstruirse.", "第4ハウスは、家やルーツ、私的な土台。居場所は受け継ぐものでも、選び直すものでもあります。", "4하우스는 집, 뿌리, 사적인 기반과 관련돼요. 소속감은 물려받거나 선택하거나 새롭게 만들어 갈 수 있어요."],
  ["House 5 concerns creativity, play, romance, and personal expression. It asks what you enjoy making or sharing without measuring the outcome.", "第五宫关联创意、玩心、浪漫与个人表达。可以思考，不计成果时你喜欢创造或分享什么。", "La casa 5 trata de creatividad, juego, romance y expresión propia. Pregunta qué disfrutas crear o compartir sin medir resultados.", "第5ハウスは、創造や遊び、ロマンス、自己表現。成果を測らずに作り、分かち合う楽しみを考えます。", "5하우스는 창작, 놀이, 로맨스, 자기표현과 관련돼요. 결과를 재지 않고 만들거나 나누는 즐거움을 생각해 봐요."],
  ["House 6 concerns daily routines, practical work, and care of the body. Use it to reflect on habits, never to infer a medical condition.", "第六宫关联日常习惯、实际工作与身体照顾。它用于反思习惯，不能判断健康状况。", "La casa 6 trata de rutinas, trabajo práctico y cuidado corporal. Sirve para reflexionar sobre hábitos, nunca para inferir una enfermedad.", "第6ハウスは、習慣や日々の仕事、体へのケア。習慣を考える視点であり、病気を判断するものではありません。", "6하우스는 일상 습관, 실무, 몸을 돌보는 일과 관련돼요. 습관을 돌아보는 데 쓰되 건강 상태를 판단하지 않아요."],
  ["House 7 concerns one-to-one partnerships and agreements. It invites attention to reciprocity, without deciding a relationship's fate.", "第七宫关联一对一关系与约定。它邀请你留意互惠，不决定一段关系的命运。", "La casa 7 trata de asociaciones y acuerdos entre dos personas. Invita a observar la reciprocidad sin decidir el destino de un vínculo.", "第7ハウスは、一対一の関係や合意。関係の運命を決めず、互いのやり取りに目を向けます。", "7하우스는 일대일 관계와 합의에 관련돼요. 관계의 운명을 결정하지 않고 서로 주고받는 방식을 살펴봐요."],
  ["House 8 concerns shared resources, trust, and consequential exchanges. Explore what is shared, what is owed, and what boundaries need agreement.", "第八宫关联共同资源、信任与影响深远的交换。可以思考共享、责任，以及需要协商的界限。", "La casa 8 trata de recursos compartidos, confianza e intercambios importantes. Explora lo compartido, las obligaciones y los límites que acordar.", "第8ハウスは、共有する資源や信頼、深く関わる交換。何を分け合い、どんな境界に合意するかを考えます。", "8하우스는 공유 자원, 신뢰, 중요한 교류와 관련돼요. 무엇을 나누고 어떤 책임과 경계를 합의할지 살펴봐요."],
  ["House 9 concerns wider learning, travel, and systems of belief. Its theme is expanding perspective, not having the final answer.", "第九宫关联进阶学习、远行与信念体系。主题是拓展视角，而不是握有最终答案。", "La casa 9 trata de estudios amplios, viajes y creencias. Su tema es ampliar la perspectiva, no poseer la respuesta definitiva.", "第9ハウスは、広い学びや旅、信念の体系。最終回答を持つことより、視点を広げる領域です。", "9하우스는 폭넓은 배움, 여행, 신념 체계와 관련돼요. 최종 답을 갖기보다 시야를 넓히는 주제예요."],
  ["House 10 concerns public contribution, vocation, and responsibility. It offers questions about direction rather than a promised career outcome.", "第十宫关联公共贡献、志业与责任。它带来方向上的问题，不承诺事业结果。", "La casa 10 trata de contribución pública, vocación y responsabilidad. Ofrece preguntas sobre dirección, no promesas profesionales.", "第10ハウスは、社会での貢献や仕事の方向、責任。職業上の成功を約束せず、進み方を考えます。", "10하우스는 사회적 기여, 소명, 책임과 관련돼요. 직업적 결과를 약속하기보다 방향에 관한 질문을 던져요."],
  ["House 11 concerns friendships, communities, and shared hopes. Consider where you contribute and where a group supports your becoming.", "第十一宫关联朋友、群体与共同愿望。可以思考你在哪里贡献，以及哪些群体支持你的成长。", "La casa 11 trata de amistades, comunidades y esperanzas compartidas. Piensa dónde aportas y qué grupos apoyan tu desarrollo.", "第11ハウスは、友情やコミュニティ、共有する希望。貢献する場と、成長を支えてくれる集まりを考えます。", "11하우스는 우정, 공동체, 함께 바라는 미래와 관련돼요. 내가 기여하는 곳과 성장을 지지하는 모임을 살펴봐요."],
  ["House 12 concerns retreat, reflection, and what happens outside public view. Solitude can offer perspective; the placement is not a diagnosis or sentence.", "第十二宫关联退隐、反思与不在公众视野内的生活。独处能带来视角，配置不是诊断或判决。", "La casa 12 trata de retiro, reflexión y vida fuera de la mirada pública. La soledad puede dar perspectiva; no es un diagnóstico ni una condena.", "第12ハウスは、ひとりの時間や内省、人目に触れない領域。配置は診断でも、避けられない運命でもありません。", "12하우스는 물러나 쉬는 시간, 성찰, 공개되지 않는 삶과 관련돼요. 혼자 있는 시간이 관점을 줄 수 있지만 배치가 진단이나 판결은 아니에요."],
];
export function houseDescription(house: number, language: HintLanguage): string {
  return astroText(language, (Number.isInteger(house) ? houses[house - 1] : undefined) ?? ["A house number from 1 to 12 is needed for this explanation.", "此说明需要第一至第十二宫的有效宫位。", "Esta explicación requiere una casa del 1 al 12.", "この説明には、1から12のハウス番号が必要です。", "이 설명에는 1부터 12까지의 하우스 번호가 필요해요."]);
}

const aspects: Record<string, { name: AstroCopy; description: AstroCopy }> = {
  conjunction: { name: ["Conjunction", "合相", "Conjunción", "コンジャンクション", "합"], description: ["A conjunction centers on 0°: two points occupy a similar zodiac position. Their themes combine; the planets involved determine whether that feels simple or complicated.", "合相以0°为中心，两个配置点处于相近的黄道位置。主题相互结合，具体感受取决于参与的行星。", "La conjunción se centra en 0°: dos puntos están próximos en el zodiaco. Sus temas se combinan; los planetas aportan el contexto.", "コンジャンクションの基準角は0°。近い黄道位置にある二つのテーマが重なり、どの天体かによって文脈が変わります。", "합의 기준 각도는 0°로, 두 지점이 황도에서 가까이 있어요. 주제가 결합하며 어떤 천체인지에 따라 맥락이 달라져요."] },
  sextile: { name: ["Sextile", "六分相", "Sextil", "セクスタイル", "육분위"], description: ["A sextile centers on 60° and symbolizes a workable connection. It suggests a possibility to engage with, not a benefit that arrives without participation.", "六分相以60°为中心，象征可合作的连结。它提供可参与的可能，不代表好处会自动发生。", "El sextil se centra en 60° y simboliza una conexión aprovechable. Sugiere una posibilidad que requiere participación, no un beneficio automático.", "セクスタイルの基準角は60°で、活かせるつながりの象徴。自動的な恩恵ではなく、関わることで開く可能性です。", "육분위의 기준 각도는 60°이며 활용할 수 있는 연결을 상징해요. 자동으로 얻는 혜택보다 참여할 수 있는 가능성이에요."] },
  square: { name: ["Square", "四分相", "Cuadratura", "スクエア", "사분위"], description: ["A square centers on 90° and symbolizes themes that pull against each other. It can invite adjustment and practice; it does not guarantee conflict or failure.", "四分相以90°为中心，象征彼此拉扯的主题。它邀请调整与练习，不保证冲突或失败。", "La cuadratura se centra en 90° y simboliza temas en tensión. Puede invitar a ajustar y practicar; no garantiza conflicto ni fracaso.", "スクエアの基準角は90°で、互いに引っ張り合うテーマの象徴。調整や練習の視点であり、失敗を決めるものではありません。", "사분위의 기준 각도는 90°이며 서로 당기는 주제를 상징해요. 조정과 연습을 생각할 수 있지만 갈등이나 실패를 뜻하지는 않아요."] },
  trine: { name: ["Trine", "三分相", "Trígono", "トライン", "삼분위"], description: ["A trine centers on 120° and symbolizes an easier flow between themes. Familiar ease can support you, but it still benefits from conscious use.", "三分相以120°为中心，象征主题之间较顺畅的流动。熟悉的便利可以支持你，也值得有意识地运用。", "El trígono se centra en 120° y simboliza fluidez entre temas. La facilidad puede apoyar, pero conviene usarla de forma consciente.", "トラインの基準角は120°で、テーマが流れやすいつながりの象徴。自然な強みも、意識して使うことで役立ちます。", "삼분위의 기준 각도는 120°이며 주제 사이의 원활한 흐름을 상징해요. 익숙한 편안함도 의식적으로 활용할 때 도움이 돼요."] },
  opposition: { name: ["Opposition", "对分相", "Oposición", "オポジション", "충"], description: ["An opposition centers on 180°: points face each other across the zodiac. It invites awareness of both needs and a workable balance, not choosing a permanent winner.", "对分相以180°为中心，两个配置点位于黄道两端。它邀请你看见双方需要并寻找平衡，而不是决定谁永远胜出。", "La oposición se centra en 180°: dos puntos se enfrentan en el zodiaco. Invita a reconocer ambas necesidades y negociar un equilibrio.", "オポジションの基準角は180°で、黄道上の向かい合う位置です。どちらかを勝たせず、両方の必要を意識して調整します。", "충의 기준 각도는 180°로, 두 지점이 황도에서 마주 봐요. 한쪽을 영원한 승자로 정하기보다 양쪽의 필요를 알아보고 균형을 찾아요."] },
};
function aspectKey(type: string): string {
  const key = type.trim().toLowerCase();
  if (key === "conjunct" || key === "conj") return "conjunction";
  if (key === "opposite" || key === "opp") return "opposition";
  return key;
}
export function aspectName(type: string, language: HintLanguage): string { const row = aspects[aspectKey(type)]; return row ? astroText(language, row.name) : type; }
export function aspectDescription(type: string, language: HintLanguage): string {
  const row = aspects[aspectKey(type)];
  return astroText(language, row?.description ?? ["An aspect describes an angular relationship between chart points. Its meaning needs the aspect type and the points involved.", "相位描述配置点之间的角度关系，需要结合相位类型与参与的配置点理解。", "Un aspecto describe una relación angular entre puntos. Para interpretarlo hacen falta el tipo y los puntos implicados.", "アスペクトは配置点どうしの角度関係。理解するには、種類と関わるポイントが必要です。", "각은 차트 지점 사이의 각도 관계를 말해요. 종류와 관련된 지점을 함께 살펴야 의미를 이해할 수 있어요."]);
}
