import type { HintLanguage } from "@/lib/i18n";
import { astroText, type AstroCopy } from "./astrologyCopy";
const copy = {
  reports: [
    "Your celestial letters",
    "你的星空来信",
    "Tus cartas celestes",
    "星からの手紙",
    "별이 보내는 편지",
  ],
  natal: [
    "Your birth chart, unfolded",
    "展开你的出生星盘",
    "Tu carta natal, desplegada",
    "出生図をひもとく",
    "나의 출생 차트 펼치기",
  ],
  together: [
    "The letter between you",
    "写给你们的星空来信",
    "La carta entre ustedes",
    "ふたりの間にある手紙",
    "두 사람 사이의 편지",
  ],
  togetherEyebrow: [
    "Two skies in conversation",
    "两片星空的对话",
    "Dos cielos en diálogo",
    "ふたつの空の対話",
    "두 하늘의 대화",
  ],
  open: [
    "Read the full report",
    "阅读完整报告",
    "Leer el informe completo",
    "レポートを読む",
    "전체 리포트 읽기",
  ],
  save: [
    "Save this letter",
    "保存这封信",
    "Guardar esta carta",
    "この手紙を保存",
    "이 편지 저장",
  ],
  saving: [
    "Saving on this device…",
    "正在保存到此设备…",
    "Guardando en este dispositivo…",
    "この端末に保存中…",
    "이 기기에 저장 중…",
  ],
  saved: [
    "Saved on this device",
    "已保存到此设备",
    "Guardado en este dispositivo",
    "この端末に保存済み",
    "이 기기에 저장됨",
  ],
  saveError: [
    "This letter is still open, but could not be saved. Try again.",
    "来信仍在当前画面，但保存失败，请重试。",
    "La carta sigue abierta, pero no se pudo guardar. Inténtalo de nuevo.",
    "手紙は開いたままですが、保存できませんでした。再試行してください。",
    "편지는 열려 있지만 저장하지 못했어요. 다시 시도해 주세요.",
  ],
  archive: [
    "Saved letters",
    "已保存的来信",
    "Cartas guardadas",
    "保存した手紙",
    "저장한 편지",
  ],
  empty: [
    "Letters you save will be here, ready to read offline.",
    "保存的来信会出现在这里，可离线重读。",
    "Tus cartas guardadas aparecerán aquí para leer sin conexión.",
    "保存した手紙はここでオフラインでも読めます。",
    "저장한 편지는 여기에서 오프라인으로도 읽을 수 있어요.",
  ],
  loadError: [
    "Saved letters could not be opened. Retry without leaving this page.",
    "无法打开已保存的来信，请在此重试。",
    "No se pudieron abrir las cartas guardadas. Vuelve a intentarlo aquí.",
    "保存した手紙を開けませんでした。ここで再試行できます。",
    "저장한 편지를 열 수 없어요. 여기에서 다시 시도해 주세요.",
  ],
  retry: ["Try again", "重试", "Reintentar", "再試行", "다시 시도"],
  contents: [
    "Inside this letter",
    "来信目录",
    "Dentro de esta carta",
    "この手紙の内容",
    "이 편지의 내용",
  ],
  evidence: [
    "See this in the chart",
    "在星盘中查看",
    "Ver en la carta",
    "チャートで確認",
    "차트에서 보기",
  ],
  partial: [
    "A partial letter",
    "部分报告",
    "Una carta parcial",
    "一部の配置による手紙",
    "일부 배치로 쓴 편지",
  ],
  partialNote: [
    "This reading uses only the positions received. Missing time, houses or aspects are not filled in.",
    "本报告仅使用已取得的配置，不补猜未知时间、宫位或相位。",
    "Esta lectura usa solo las posiciones recibidas. No completa horas, casas ni aspectos ausentes.",
    "取得できた配置だけを使用します。不明な時刻、ハウス、アスペクトは推測しません。",
    "확인된 배치만 사용해요. 모르는 시간, 하우스, 각은 추측하지 않아요.",
  ],
  snapshot: [
    "This letter reflects the birth details used to create it. Save it to keep this version when those details change.",
    "这封信依据生成时的出生资料写成。保存后，即使资料改变，也能保留这个版本。",
    "Esta carta refleja los datos de nacimiento usados para crearla. Guárdala para conservar esta versión si cambian esos datos.",
    "作成時の出生情報をもとにした手紙です。保存すると、情報を変更してもこの版を残せます。",
    "이 편지는 작성에 사용한 출생 정보를 담고 있어요. 저장하면 정보를 바꿔도 이 버전을 간직할 수 있어요.",
  ],
  overview: [
    "The opening lines",
    "来信的开篇",
    "Las primeras líneas",
    "はじめの言葉",
    "편지의 첫 문장",
  ],
  emotions: [
    "What helps you feel at home",
    "让内心安定的事",
    "Lo que te hace sentir en casa",
    "心が落ち着く場所",
    "마음이 편안해지는 것",
  ],
  communication: [
    "Your way with words",
    "你的沟通方式",
    "Tu manera de comunicar",
    "言葉の使い方",
    "나의 소통 방식",
  ],
  relationships: [
    "Affection & connection",
    "爱意与连接",
    "Afecto y conexión",
    "愛情とつながり",
    "애정과 연결",
  ],
  action: [
    "How you begin",
    "你如何行动",
    "Cómo das el primer paso",
    "一歩を踏み出すとき",
    "첫걸음을 내딛는 방식",
  ],
  growth: [
    "Room to grow",
    "成长的空间",
    "Espacio para crecer",
    "成長の余白",
    "성장할 공간",
  ],
  houses: [
    "Where life unfolds",
    "生活展开的领域",
    "Dónde se despliega la vida",
    "人生が広がる場所",
    "삶이 펼쳐지는 영역",
  ],
  aspects: [
    "The conversation within",
    "配置之间的对话",
    "La conversación interior",
    "配置どうしの対話",
    "배치 사이의 대화",
  ],
  friction: [
    "Working with differences",
    "与差异相处",
    "Convivir con las diferencias",
    "違いと向き合う",
    "차이를 이해하기",
  ],
  cooperation: [
    "Making space for each other",
    "为彼此留出空间",
    "Hacer espacio para el otro",
    "お互いの余白をつくる",
    "서로를 위한 공간",
  ],
  you: ["Your chart", "你的星盘", "Tu carta", "あなたのチャート", "내 차트"],
  partner: [
    "Their chart",
    "对方的星盘",
    "Su carta",
    "相手のチャート",
    "상대의 차트",
  ],
  both: [
    "Both charts",
    "双人星盘",
    "Ambas cartas",
    "ふたりのチャート",
    "두 사람 차트",
  ],
  list: [
    "All connections",
    "全部相位",
    "Todas las conexiones",
    "すべてのつながり",
    "모든 연결",
  ],
  layers: [
    "Chart layers",
    "星盘图层",
    "Capas de la carta",
    "チャートのレイヤー",
    "차트 레이어",
  ],
  orb: ["Orb", "容许度", "Orbe", "オーブ", "오브"],
  separation: [
    "Angular separation",
    "实际夹角",
    "Separación angular",
    "角距離",
    "실제 각거리",
  ],
  policy: [
    "Compared from actual tropical longitudes. Hint policy v1: conjunction / opposition 8°, trine / square 6°, sextile 4°. These are reading conventions, not relationship scores.",
    "依据实际回归黄道黄经比较。Hint v1：合相／对分 8°，三分／四分 6°，六分 4°。这是解读采用的范围，不是关系评分。",
    "Comparación de longitudes tropicales reales. Hint v1: conjunción / oposición 8°, trígono / cuadratura 6°, sextil 4°. Son convenciones de lectura, no puntuaciones de relación.",
    "実際のトロピカル黄経を比較。Hint v1：合／衝8°、三分／四分6°、六分4°。読み解きの規則であり、関係の点数ではありません。",
    "실제 열대황도 경도를 비교해요. Hint v1: 합 / 충 8°, 삼분 / 사분 6°, 육분 4°. 해석에 쓰는 기준이며 관계 점수가 아니에요.",
  ],
  balance: [
    "The elements in your chart",
    "星盘中的元素",
    "Los elementos de tu carta",
    "チャートのエレメント",
    "차트 속 원소",
  ],
  balanceNote: [
    "Each returned planet counts once; the Ascendant is excluded. Ties remain ties.",
    "每颗已取得的行星计一次，不计上升点；并列结果保持并列。",
    "Cada planeta recibido cuenta una vez; se excluye el Ascendente. Los empates se conservan.",
    "取得した天体を各1回数え、アセンダントは除きます。同数は同数のままです。",
    "확인된 천체를 한 번씩 세고 상승점은 제외해요. 동률은 그대로 표시해요.",
  ],
  relation: [
    "How the themes meet",
    "这些主题如何关联",
    "Cómo se encuentran los temas",
    "テーマが出会うとき",
    "주제들이 만나는 방식",
  ],
  practice: [
    "A small practice",
    "一个小练习",
    "Una pequeña práctica",
    "小さな実践",
    "작은 실천",
  ],
  howToRead: [
    "Read a chart, one layer at a time",
    "一层一层，读懂星盘",
    "Lee la carta, capa a capa",
    "ひとつずつチャートを読む",
    "한 겹씩 차트 읽기",
  ],
  connection: [
    "The relationship",
    "配置间的关系",
    "La relación",
    "関係",
    "배치 간 관계",
  ],
  unavailable: [
    "No verified positions are available for this section yet.",
    "此章节尚无可核对的配置资料。",
    "Aún no hay posiciones verificadas para esta sección.",
    "この章には確認できる配置がまだありません。",
    "이 부분에 확인된 배치가 아직 없어요.",
  ],
  originalLanguage: [
    "Saved language",
    "保存时的语言",
    "Idioma guardado",
    "保存時の言語",
    "저장한 언어",
  ],
} satisfies Record<string, AstroCopy>;
export type ReportCopyKey = keyof typeof copy;
export const rt = (language: HintLanguage, key: ReportCopyKey) =>
  astroText(language, copy[key]);
