import type { HintLanguage } from "../../lib/i18n";

type ExitCopy = { title: string; tarot: string; other: string; kept: string; stay: string; leave: string; leftTitle: string; left: string; okay: string };
export const ROOM_EXIT_COPY: Record<HintLanguage, ExitCopy> = {
  en: { title: "Leave this space?", tarot: "Your unfinished Tarot reading will reset. When you return, you’ll begin with a new question.", other: "When you return, this space will open at the beginning. Saved drafts can be reopened when you choose.", kept: "Saved readings, personal details and today’s cards are kept.", stay: "Stay here", leave: "Leave and start fresh", leftTitle: "A fresh start next time", left: "You’ve left this space. Your next visit begins at the beginning; saved records and drafts are still available.", okay: "Got it" },
  zh: { title: "离开这个空间？", tarot: "本次未完成的塔罗阅读将重设。再次进入时，会从新的问题开始。", other: "再次进入时，这个空间会回到起点。已保存的草稿可由你选择恢复。", kept: "已保存的阅读、个人资料和今日牌都会保留。", stay: "留在这里", leave: "离开并重新开始", leftTitle: "下次，从新开始", left: "你已离开这个空间。下次进入会从起点开始，已保存的记录和草稿仍可查看。", okay: "知道了" },
  es: { title: "¿Salir de este espacio?", tarot: "Esta lectura de tarot sin terminar se reiniciará. Al volver, empezarás con una nueva pregunta.", other: "Al volver, este espacio se abrirá desde el principio. Puedes recuperar los borradores guardados cuando quieras.", kept: "Se conservan las lecturas guardadas, tus datos personales y las cartas de hoy.", stay: "Quedarme aquí", leave: "Salir y empezar de nuevo", leftTitle: "Un nuevo comienzo", left: "Has salido de este espacio. La próxima visita empieza desde el principio; tus registros y borradores guardados siguen disponibles.", okay: "Entendido" },
  ja: { title: "この空間を離れますか？", tarot: "途中のタロットリーディングはリセットされます。次に入ると、新しい質問から始まります。", other: "次に入ると最初の画面に戻ります。保存済みの下書きは、選んで再開できます。", kept: "保存済みのリーディング、プロフィール、今日のカードは保持されます。", stay: "ここに留まる", leave: "離れて新しく始める", leftTitle: "次は新しい始まりから", left: "この空間を離れました。次回は最初から始まります。保存済みの記録と下書きは引き続き利用できます。", okay: "わかりました" },
  ko: { title: "이 공간을 나갈까요?", tarot: "진행 중인 타로 리딩이 초기화됩니다. 다시 들어오면 새로운 질문부터 시작합니다.", other: "다시 들어오면 첫 화면부터 시작합니다. 저장된 초안은 원할 때 이어갈 수 있습니다.", kept: "저장된 리딩, 프로필과 오늘의 카드는 유지됩니다.", stay: "여기에 머물기", leave: "나가고 새로 시작하기", leftTitle: "다음에는 새로운 시작", left: "이 공간을 나왔습니다. 다음 방문은 처음부터 시작하며 저장된 기록과 초안은 계속 확인할 수 있습니다.", okay: "확인" },
};
