import type { HintLanguage } from "./i18n";

const rows: Array<[string, string, string, string, string, string]> = [
  ["legal.privacy.item1", "Local beta profiles keep device content separate. When connected, a server-issued device credential protects saved server data; an anonymous browser ID alone does not grant access.", "本机 beta 档案分别保存设备内容。连接服务器后，由服务器签发的设备凭证保护已保存的数据；匿名浏览器 ID 本身不能取得访问权限。", "Los perfiles beta locales separan el contenido del dispositivo. Una credencial emitida por el servidor protege los datos guardados en él; un identificador anónimo del navegador no da acceso por sí solo.", "端末内のベータプロフィールごとに内容を分けて保存します。接続時はサーバー発行のデバイス認証情報で保存データを保護します。匿名のブラウザIDだけではアクセスできません。", "기기 내 베타 프로필별로 내용을 구분합니다. 연결 시 서버에서 발급한 기기 인증 정보로 저장 데이터를 보호하며, 익명 브라우저 ID만으로는 접근할 수 없습니다."],
  ["legal.privacy.item2", "Birth details and saved content may be stored on the beta server. Requested readings and chart calculations send the relevant question, conversation or birth details to the configured service. Save status shows whether content is local or synced.", "出生资料与保存的内容可能存入 beta 服务器。请求解读或星盘计算时，会将相关问题、对话或出生资料发送至相应服务。保存状态会区分本机保存与已同步。", "Los datos de nacimiento y el contenido guardado pueden almacenarse en el servidor beta. Las lecturas y los cálculos envían la pregunta, conversación o datos de nacimiento pertinentes al servicio configurado. El estado indica si están guardados localmente o sincronizados.", "出生情報や保存した内容はベータサーバーにも保存される場合があります。リーディングやチャートの計算を依頼すると、必要な質問・会話・出生情報を該当サービスに送信します。保存状態で端末内保存と同期済みを区別します。", "출생 정보와 저장한 내용은 베타 서버에도 저장될 수 있습니다. 리딩이나 차트 계산을 요청하면 관련 질문, 대화 또는 출생 정보가 해당 서비스로 전송됩니다. 저장 상태에서 기기 저장과 동기화를 구분합니다."],
  ["legal.privacy.item3", "Clear History removes this local profile's readings, journals and created compatibility invitations/results after the server deletion succeeds. It preserves your birth profile, settings and daily card locks. Created invitation links stop working. Contact support about other stored data or provider retention.", "服务器删除成功后，清除历史会移除此本机档案的解读、日记及所建立的合盘邀请与结果。出生资料、设置与当日牌锁定会保留，已建立的邀请链接将失效。其他保存的数据及服务商留存问题请联系支持。", "Borrar el historial elimina las lecturas, diarios e invitaciones y resultados creados por este perfil local cuando el servidor confirma la eliminación. Conserva los datos de nacimiento, ajustes y cartas diarias fijadas; los enlaces creados dejan de funcionar. Contacta con soporte sobre otros datos y la retención de los proveedores.", "サーバーでの削除が完了すると、この端末内プロフィールのリーディング・日記・作成した相性の招待と結果を削除します。出生情報・設定・当日のカード固定情報は保持し、作成済み招待リンクは無効になります。その他の保存データやサービス提供元の保持期間についてはサポートにお問い合わせください。", "서버 삭제가 완료되면 이 로컬 프로필의 리딩, 일기 및 생성한 궁합 초대와 결과가 삭제됩니다. 출생 정보, 설정과 당일 카드 고정 정보는 유지되며, 생성한 초대 링크는 작동하지 않습니다. 다른 저장 데이터와 제공업체의 보관 정책은 지원팀에 문의하세요."],
  ["legal.about.item3", "This is a local beta with device-protected server access. Demo codes do not verify email or phone ownership. Formal sign-in, email/SMS delivery and cross-device account synchronization are not connected. Dream and deep astrology reports remain previews.", "这是具有设备访问保护的本机 beta。演示码不会验证邮箱或电话的所有权。正式登录、邮件与短信发送及跨设备账号同步尚未连接。梦境完整解读与深入占星报告仍为预览。", "Esta beta usa perfiles locales y acceso al servidor protegido por dispositivo. Los códigos de prueba no verifican correos ni teléfonos. El acceso formal, el envío de correo/SMS y la sincronización de cuentas entre dispositivos no están conectados. Sueños y los informes astrológicos detallados siguen en vista previa.", "端末ごとにサーバーへのアクセスを保護するローカルベータです。デモコードでメールや電話の所有者確認はできません。正式なログイン・メール/SMS配信・端末間のアカウント同期は未接続です。夢の詳細解釈と詳しい占星術レポートはプレビューです。", "기기별 서버 접근을 보호하는 로컬 베타입니다. 데모 코드는 이메일이나 전화번호의 소유권을 확인하지 않습니다. 정식 로그인, 이메일/SMS 전송 및 기기 간 계정 동기화는 연결되지 않았습니다. 꿈 상세 해석과 심층 점성술 보고서는 미리보기입니다."],
];
export const RELEASE_COPY = Object.fromEntries((["en", "zh", "es", "ja", "ko"] as HintLanguage[]).map((language, index) => [language, Object.fromEntries(rows.map(row => [row[0], row[index + 1]]))])) as Record<HintLanguage, Record<string, string>>;
